#!/bin/bash
# The FSL command topup is incapable of handling the scenario where
#   its multi-resolution registration pyramid involves downsampling
#   but an image axis is not a whole multiple of that downsampling factor
# Support for such data was subsequently offered within the FSL software
#   by providing alternative configuration files that did not involve downsampling;
#   while this facilitates processing, it also increases execution time
# To facilitate processing with the same configuration file,
#   any image spatial axis that is not a multiple of 2
#   (the downsampling factor utilised in the default topup configuration file)
#   is padded with a duplicate of the last slice,
#   so that the images provided to topup & eddy have all spatial axes with size a multiple of 2;
#   the resulting image data then have the excess slice removed from the data
# This is simulated using input data that do have dimensions being a factor of 2
#   by removing one slice prior to giving the image data as input to dwifslpreproc
mrconvert BIDS/sub-04/dwi/sub-04_dwi.nii.gz tmp-sub-04_dwi.mif -force \
-fslgrad BIDS/sub-04/dwi/sub-04_dwi.bvec BIDS/sub-04/dwi/sub-04_dwi.bval \
-json_import BIDS/sub-04/dwi/sub-04_dwi.json \
-coord 0 0:46 -coord 1 1:47 -force

mrconvert BIDS/sub-04/fmap/sub-04_dir-1_epi.nii.gz tmp-sub-04_dir-1_epi.mif -force \
-json_import BIDS/sub-04/fmap/sub-04_dir-1_epi.json
mrconvert BIDS/sub-04/fmap/sub-04_dir-2_epi.nii.gz tmp-sub-04_dir-2_epi.mif -force \
-json_import BIDS/sub-04/fmap/sub-04_dir-2_epi.json
mrcat tmp-sub-04_dir-1_epi.mif tmp-sub-04_dir-2_epi.mif tmp-sub-04_dir-all_epi.mif -axis 3 - | \
mrconvert - tmp-sub-04_dir-all_epi.mif -force \
-coord 0 0:46 -coord 1 1:47

dwifslpreproc tmp-sub-04_dwi.mif tmp.mif -force \
-pe_dir ap -readout_time 0.1 \
-rpe_pair -se_epi tmp-sub-04_dir-all_epi.mif

testing_diff_header tmp.mif dwifslpreproc/axis_padding.mif.gz
