#!/bin/bash
# Ensure that dwifslpreproc executes successfully
#  whenever pipes are used to specify different images

# Input and output DWIs are pipes
mrconvert BIDS/sub-04/dwi/sub-04_dwi.nii.gz - \
-fslgrad BIDS/sub-04/dwi/sub-04_dwi.bvec BIDS/sub-04/dwi/sub-04_dwi.bval \
-json_import BIDS/sub-04/dwi/sub-04_dwi.json \
-strides 0,0,0,1 | \
dwifslpreproc - - \
-pe_dir ap -readout_time 0.1 -rpe_none \
testing_diff_header - dwifslpreproc/rpenone_default.mif.gz

# Input SE-EPI series is a pipe
mrconvert BIDS/sub-04/fmap/sub-04_dir-1_epi.nii.gz tmp1.mif -force \
-json_import BIDS/sub-04/fmap/sub-04_dir-1_epi.json
mrconvert BIDS/sub-04/fmap/sub-04_dir-2_epi.nii.gz tmp2.mif -force \
-json_import BIDS/sub-04/fmap/sub-04_dir-2_epi.json
mrcat tmp1.mif tmp2.mif -axis 3 - | \
dwifslpreproc BIDS/sub-04/dwi/sub-04_dwi.nii.gz tmp.mif -force \
-fslgrad BIDS/sub-04/dwi/sub-04_dwi.bvec BIDS/sub-04/dwi/sub-04_dwi.bval \
-pe_dir ap -readout_time 0.1 -rpe_pair \
-se_epi -
testing_diff_header tmp.mif dwifslpreproc/rpepair_default.mif.gz
