#!/bin/bash
# Ensure that the outputs match those generated
#   with a fairly up-to-date version of the software
# (verification that results match a much older version of the software
#   is performed in a separate test)
rm -rf tmp/
mkdir tmp/

mrclusterstats mrclusterstats/subjects.txt mrclusterstats/design.txt mrclusterstats/contrast.txt SIFT_phantom/mask.mif tmp/
testing_diff_image tmp/abs_effect.mif mrclusterstats/default/abs_effect.mif
testing_diff_image tmp/beta0.mif mrclusterstats/default/beta0.mif
testing_diff_image tmp/beta1.mif mrclusterstats/default/beta1.mif
testing_diff_image tmp/std_dev.mif mrclusterstats/default/std_dev.mif
testing_diff_image tmp/std_effect.mif mrclusterstats/default/std_effect.mif
testing_diff_image tmp/tfce.mif mrclusterstats/default/tfce.mif
testing_diff_image tmp/tvalue.mif mrclusterstats/default/tvalue.mif
testing_diff_image tmp/Zstat.mif mrclusterstats/default/Zstat.mif

# Ensure that the statistical significance mask matches
#   the synthetic effect that was introduced in the data
mrcalc tmp/fwe_1mpvalue.mif 0.95 -gt - | \
testing_diff_image - SIFT_phantom/upper.mif

