#!/bin/bash
# Verify default operation of the "fixelvalidate" command
#   with a well-formed input directory

rm -f tmp.txt
fixelvalidate fixel_image/ 2>&1 | tee tmp.txt
grep -E "fixel directory \".+\" is valid" tmp.txt
