#!/bin/bash
# Ensure that if the directions image is missing, the right error is produced.

rm -rf tmp/
mkdir tmp/
cp fixel_image/index.mif tmp/index.mif
cp fixel_image/afd.mif tmp/afd.mif

rm -f tmp.txt
! ( fixelvalidate tmp/ > tmp.txt 2>&1 )
cat tmp.txt
grep "Could not find directions image" tmp.txt
