#!/bin/bash
# Ensure that if the index image indicates an incorrect number of fixels in the header,
#   the right error is produced.

rm -rf tmp/
mkdir tmp/
mrconvert fixel_image/index.mif -set_property nfixels 1000 tmp/index.mif
#cp fixel_image/directions.mif tmp/directions.mif
mrconvert fixel_image/directions.mif tmp/directions.mif -coord 0 0:999

rm -f tmp.txt
! ( fixelvalidate tmp/ > tmp.txt 2>&1 )
cat tmp.txt
grep -E "Total number of fixels indicated in header of image \".+\" \\(.+\\) does not match that indicated in image data" tmp.txt
