#!/bin/bash
# Basic test of default operation of sh2response command
# Result is compared against that generated using a prior software version
amp2sh dwi.mif - | \
sh2response - sh2response/sf.mif sh2response/ev.mif tmp.txt -force

testing_diff_matrix tmp.txt sh2response/out.txt -frac 1e-5
