#!/bin/bash
# Verify successful operation of the "labelvalidate" command
#   when the input parcellation image contains contiguous indices

rm -f tmp.txt
labelvalidate labelconvert/out_fs.mif.gz 2>&1 | tee tmp.txt
grep -E "image values verified to be non\\-negative integers" tmp.txt
grep "Label indices: contiguous" tmp.txt
