#!/bin/bash
# Multi-contrast registration;
#   affine registration only
# Because the additional contrasts for both moving and template
#   are identical to the first contrast,
#   the outcomes of registration should not be modified in any way
#   by the presence of that additional contrast;
#   as such, the outcome is compared to the same expected outcome
#   as that generated using single-contrast registration using a prior software version
# "moving.mif.gz" and "template.mif.gz" are shared with many other tests;
#   they are therefore downsampled here rather than in the test data itself,
#   as registration cost scales with the number of voxels
mrgrid moving.mif.gz regrid -scale 0.5 tmp-moving.mif -force
mrgrid template.mif.gz regrid -scale 0.5 tmp-template.mif -force

mrregister tmp-moving.mif tmp-template.mif tmp-moving.mif tmp-template.mif \
-type affine -affine_niter 15 -transformed - | \
testing_diff_image - mrregister/out.mif.gz -abs 1e-5
