#!/bin/bash
# Multi-contrast registration;
#   affine registration only
# Because the additional contrasts for both moving and template
#   are identical to the first contrast,
#   the outcomes of registration should not be modified in any way
#   by the presence of that additional contrast;
#   as such, the outcome is compared to the same expected outcome
#   as that generated using single-contrast registration using a prior software version
mrregister moving.mif.gz template.mif.gz moving.mif.gz template.mif.gz \
-type affine -affine_niter 15 -transformed - | \
testing_diff_image - mrregister/out.mif.gz -abs 1e-5
