#!/bin/bash
# Multi-contrast registration;
#   affine only
# In this test, weights per contrast are specified.
#   Since the images are identical between the two contrasts,
#   this does not influence the outcomes of registration in any way;
#   this test therefore only ensures that that information is parsed without failure.
# "moving.mif.gz" and "template.mif.gz" are shared with many other tests;
#   they are therefore downsampled here rather than in the test data itself,
#   as registration cost scales with the number of voxels
mrgrid moving.mif.gz regrid -scale 0.5 tmp-moving.mif -force
mrgrid template.mif.gz regrid -scale 0.5 tmp-template.mif -force

mrregister tmp-moving.mif tmp-template.mif tmp-moving.mif tmp-template.mif \
-type affine -affine_niter 15 -mc_weights 1,2 -transformed - | \
testing_diff_image - mrregister/out.mif.gz -abs 1e-5
