#!/bin/bash
# Verify default operation of the "dwinormalise manual" algorithm
# Note that in this example,
#   a whole-brain mask is used for determining the reference intensity;
#   this is not a recommended use case for the algorithm,
#   it's simply used for testing here as _some_ input mask must be provided
dwinormalise manual BIDS/sub-01/dwi/sub-01_dwi.nii.gz BIDS/sub-01/dwi/sub-01_brainmask.nii.gz tmp.mif -force \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval

testing_diff_image ../tmp/dwinormalise/manual/out.mif dwinormalise/manual/out.mif.gz -frac 1e-5
