#!/bin/bash
# Verify "5ttgen freesurfer" operation when the -nocrop option is specified
5ttgen freesurfer BIDS/sub-01/anat/aparc+aseg.mgz tmp.mif -nocrop -force
testing_diff_image tmp.mif 5ttgen/freesurfer/nocrop.mif.gz
