#!/bin/bash
# Test afdconnectivity with the -afd_map option:
#   verify that the per-voxel AFD map output image is produced successfully,
#   and approximately matches what the AFD should be in each voxel
#   (which, based on scaling of the integration of FOD lobes,
#   should be close to 1.0 in each intersected voxel)
tckedit SIFT_phantom/tracks.tck -include SIFT_phantom/upper.mif tmp.tck -force
afdconnectivity -config FMLSDirectionSet 321 SIFT_phantom/fods.mif tmp.tck \
    -afd_map tmp.mif -force
testing_diff_image tmp.mif SIFT_phantom/upper.mif -frac 1.5e-3
