#!/bin/bash
# Verify the legacy brute-force partial volume estimation algorithm
# The input surface should be closed and free of inconsistencies in normal polarity
mesh2voxel -algorithm brute_force meshconvert/in_ascii.vtk meshconvert/image.mif.gz - | \
testing_diff_image - mesh2voxel/bruteforce.mif.gz -abs 1.5e-3
