#!/bin/bash
# Basic test verifying the default operation of the command (the "toblerone" algorithm)
# The input surface should be closed and free of inconsistencies in normal polarity
mesh2voxel meshconvert/in_ascii.vtk meshconvert/image.mif.gz - | \
testing_diff_image - mesh2voxel/toblerone.mif.gz -abs 1.5e-3
