#!/usr/bin/env python

import sys, os

optionlist =  [ ]

for line in sys.stdin:
  line = line.strip()
  if line.startswith ('option:'):
    optionlist += [ [ line[8:], '', '' ] ]
  elif line.startswith ('default:'):
    optionlist[-1][1] = line
  else:
    optionlist[-1][2] += line + ' '

optionlist.sort()
for entry in optionlist:
  print ('- **' + entry[0] + '**<br>')
  print ('    _' + entry[1] + '_<br>')
  print ('    ' + entry[2] + '\n')
