#!/bin/bash

# Copyright (c) 2008-2024 the MRtrix3 contributors.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Covered Software is provided under this License on an "as is"
# basis, without warranty of any kind, either expressed, implied, or
# statutory, including, without limitation, warranties that the
# Covered Software is free of defects, merchantable, fit for a
# particular purpose or non-infringing.
# See the Mozilla Public License v. 2.0 for more details.
#
# For more details, see http://www.mrtrix.org/.

LOGFILE=pylint.log
echo logging to \""$LOGFILE"\"

# generate list of tests to run:
tests="update_copyright"
if [ $# == 0 ]; then
  for filepath in $(find python/mrtrix3/ -name '*.py'); do
    tests="$tests $filepath"
  done
else
  tests="$@"
fi

success=0
ntests=0



cat > $LOGFILE <<EOD
-------------------------------------------
  Version information
-------------------------------------------

EOD

python3 -m pylint --version >> $LOGFILE

cat >> $LOGFILE <<EOD

-------------------------------------------
  Testing MRtrix3 Python scripts
-------------------------------------------

EOD


export PYTHONPATH="$(pwd)/python/lib:$PYTHONPATH"
for file in $tests; do

  cat >> $LOGFILE <<EOD
-------------------------------------------

## testing "${file}"...
EOD

  echo -n 'testing "'${file}'"... '

  python3 -m pylint --rcfile=testing/pylint.rc ${file} > .__tmp.log 2>&1

  if [[ $? -ne 0 ]]; then
    echo 'ERROR'
    echo " [ ERROR ]" >> $LOGFILE
  else
    echo 'OK'
    echo " [ ok ]" >> $LOGFILE
    ((success++))
  fi

  cat .__tmp.log >> $LOGFILE
  echo "" >> $LOGFILE
  ((ntests++))

done

if [[ ${success} -lt ${ntests} ]]; then
  cat >> $LOGFILE <<EOD

## ERROR: $(($ntests-$success)) of $(($ntests)) tests failed (see \""$LOGFILE"\")

EOD
  exit 1
else
  cat >> $LOGFILE <<EOD

## $ntests tests completed OK

EOD
fi
