#!/bin/bash -e
if [ "$1" != "-f" ]; then
  echo "This uninstaller will remove MRtrix3 from /usr/local/mrtrix3."
  echo "In addition it will:"
  echo "* remove symbolic links in /usr/local/bin to the binaries that used to be in /usr/local/mrtrix/bin"
  echo "* remove symbolic links in /Applications to the app bundles that used to be in /usr/local/mrtrix/bin"
  echo "* request that you enter your password to allow system-wide uninstallation"
  if [ ! -d "/usr/local/mrtrix3" ] ; then
    echo "ERROR: Could not find an existing installation."
    exit
  fi
  echo "Are you sure you want to continue the uninstallation?"
  select yn in "Yes" "No"; do
    case $yn in
      Yes ) break;;
      No ) exit;;
    esac
  done
fi
if [ $EUID == 0 ]; then
  if [ -f /usr/local/mrtrix3/symlinks ]; then
    echo "Removing symbolic links ..."
    for l in $(cat /usr/local/mrtrix3/symlinks); do
      if [ -L "${l}" ]; then
        unlink $l
      fi
    done
  fi
  echo "Removing installation in /usr/local/mrtrix3..."
  rm -rf "/usr/local/mrtrix3"
  echo "Unistallation complete!"
else
  exec sudo "$0" "$@" -f
fi
