#!/bin/bash


folder=$(mktemp -d)
( 
  set -e
  cd $folder
  echo Using temporary folder $folder

  git clone git@github.com:jdtournier/mrtrix3.git mrtrix3
  
  ( 
    cd mrtrix3
    ./doxygen
    ./configure
    ./build 2>/dev/null
  )

  git clone git@github.com:jdtournier/mrtrix3-dev-doc.git 
  ( 
    set -e 
    cd mrtrix3-dev-doc 
    rm -rf *
    cp -r ../mrtrix3/dev/html/* .
    git add .
    git commit -a -m "automatic update of dev doc"
    git push
  ) 
  
  
  
  git clone git@github.com:jdtournier/mrtrix3.wiki.git
  
  rm -rf mrtrix3.wiki/commands
  mkdir -p mrtrix3.wiki/commands
  
  echo '[[Home]]
  
  **Commands**<br>' > mrtrix3.wiki/commands/_Sidebar.md
  
  echo 'This section provides the documentation for every command included in
  MRtrix3. This is the same information that is displayed by each command when
  invoked without options, or with the `-help` option.
  
  Use the sidebar to access the documentation for a particular command.' >\
  mrtrix3.wiki/commands/MRtrix3-commands.md
  
  for n in mrtrix3/bin/*; do
    $n __print_usage_markdown__ > mrtrix3.wiki/commands/$(basename $n).md
    echo '[['$(basename $n)']]<br>' >> mrtrix3.wiki/commands/_Sidebar.md
  done
  
  (
    cd mrtrix3.wiki
    git add commands
    git commit -m "automatic update of command documentation"
    git push
  )
  
)
echo cleaning up...
rm -rf $folder

