#!/bin/bash

# Copyright (c) 2008-2023 the MRtrix3 contributors.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Covered Software is provided under this License on an "as is"
# basis, without warranty of any kind, either expressed, implied, or
# statutory, including, without limitation, warranties that the
# Covered Software is free of defects, merchantable, fit for a
# particular purpose or non-infringing.
# See the Mozilla Public License v. 2.0 for more details.
#
# For more details, see http://www.mrtrix.org/.

set -e
./doxygen

[ -d mrtrix3-dev-doc ] || git clone git@github.com:MRtrix3/mrtrix3-dev-doc.git

(
  cd mrtrix3-dev-doc
  git pull
  git rm -rf *
  cp -r ../devdoc/* .
  touch .nojekyll
  git add .
  git commit -a -m "automatic update of dev doc"
  git push
)


