#!/bin/bash


folder=$(mktemp -d)
( 
  set -e
  cp format_config_options $folder
  cd $folder
  echo Using temporary folder $folder

  git clone git@github.com:MRtrix3/mrtrix3.git mrtrix3
  
  ( 
    cd mrtrix3
    ./doxygen
    ./configure
    ./build 2>/dev/null
  )

  git clone git@github.com:MRtrix3/mrtrix3-dev-doc.git 
  ( 
    set -e 
    cd mrtrix3-dev-doc 
    rm -rf *
    cp -r ../mrtrix3/dev/html/* .
    git add .
    git commit -a -m "automatic update of dev doc"
    git push
  ) 
  
  
  
  git clone git@github.com:MRtrix3/mrtrix3.wiki.git
  
  rm -rf mrtrix3.wiki/commands/list
  mkdir -p mrtrix3.wiki/commands/list
  rm -rf mrtrix3.wiki/scripts/list
  mkdir -p mrtrix3.wiki/scripts/list
  
  echo '[[Home]]

[[MRtrix 0.2 equivalent commands]]
  
**Commands**<br>
' > mrtrix3.wiki/commands/_Sidebar.md
  
  for n in mrtrix3/bin/*; do
    $n __print_usage_markdown__ > mrtrix3.wiki/commands/list/$(basename $n).md
    echo '[['$(basename $n)']]<br>' >> mrtrix3.wiki/commands/_Sidebar.md
  done

  echo '[[Home]]

**Scripts**<br>
' >> mrtrix3.wiki/scripts/_Sidebar.md

  for n in `find mrtrix3/scripts/ -type f -print0 | xargs -0 grep -l "lib.app.initParser"`; do
    $n __print_usage_markdown__ > mrtrix3.wiki/scripts/list/$(basename $n).md
    echo '[['$(basename $n)']]<br>' >> mrtrix3.wiki/scripts/_Sidebar.md
  done

  grep -rn --include=\*.h --include=\*.cpp '^\s*//CONF\b ' mrtrix3 | sed -ne 's/^.*CONF \(.*\)/\1/p' | ./format_config_options > mrtrix3.wiki/DesignPrinciples/List-of-configuration-file-options.md

  
  (
    cd mrtrix3.wiki
    git add commands scripts DesignPrinciples/List-of-configuration-file-options.md
    git commit -m "automatic update of command and script documentation"
    git push
  )
  
)
echo cleaning up...
rm -rf $folder

