#!/bin/bash
# Verify import of an ITK format file from ANTs
#   that includes values in the "FixedParameters" field
# Outcome is compared to that generated using a prior software version
transformconvert transformconvert/affine_ants.txt itk_import tmp.txt -force
testing_diff_matrix tmp.txt transformconvert/affine_mrtrix.txt -abs 1e-3
