#!/bin/bash
# Verify operation of the dwishellmath command
#   when image paths include whitespace characters
rm -rf "tmp scratch"

ln -s BIDS/sub-01/dwi/sub-01_dwi.nii.gz "tmp in.nii.gz"
ln -s BIDS/sub-01/dwi/sub-01_dwi.bvec "tmp in.bvec"
ln -s BIDS/sub-01/dwi/sub-01_dwi.bval "tmp in.bval"

mkdir "tmp scratch"

dwishellmath "tmp in.nii.gz" mean "tmp out.mif" -force \
-fslgrad "tmp in.bvec" "tmp in.bval" \
-scratch "tmp scratch"

ls | grep "^tmp out\.mif$"
