#!/bin/bash
# Verify operation of command
#   when utilising image pipes

# Input and output parcellation images are pipes
mrconvert BIDS/sub-01/anat/sub-01_parc-desikan_indices.nii.gz - | \
labelsgmfirst - BIDS/sub-01/anat/sub-01_T1w.nii.gz BIDS/parc-desikan_lookup.txt - | \
testing_diff_header - labelsgmfirst/default.mif.gz

# Input T1-weighted image is a pipe
mrconvert BIDS/sub-01/anat/sub-01_T1w.nii.gz - | \
labelsgmfirst BIDS/sub-01/anat/sub-01_parc-desikan_indices.nii.gz - BIDS/parc-desikan_lookup.txt tmp.mif -force
testing_diff_header tmp.mif labelsgmfirst/default.mif.gz
