#!/bin/bash
# vectorstats test 0
# 
# Prior version where test data were generated dynamically:
# N=16 SNR=5 vectorstats/gen0.py
# vectorstats tmpsubjects.txt tmpdesign.csv tmpcontrast.csv tmpout -ftests tmpftests.csv -force
# vectorstats/test0.py
# This is no longer used in order to avoid random failures
vectorstats vectorstats/0/subjects.txt vectorstats/0/design.csv vectorstats/0/contrast.csv tmpout -ftests vectorstats/0/ftests.csv -force
testing_diff_matrix tmpoutFvalue_F1.csv vectorstats/0/outFvalue_F1.csv -frac 1e-6
testing_diff_matrix tmpoutFvalue_F2.csv vectorstats/0/outFvalue_F2.csv -frac 1e-6
testing_diff_matrix tmpoutZstat_F1.csv vectorstats/0/outZstat_F1.csv -frac 1e-6
testing_diff_matrix tmpoutZstat_F2.csv vectorstats/0/outZstat_F2.csv -frac 1e-6
testing_diff_matrix tmpoutZstat_t1.csv vectorstats/0/outZstat_t1.csv -frac 1e-6
testing_diff_matrix tmpoutZstat_t2.csv vectorstats/0/outZstat_t2.csv -frac 1e-6
testing_diff_matrix tmpoutZstat_t3.csv vectorstats/0/outZstat_t3.csv -frac 1e-6
testing_diff_matrix tmpoutabs_effect_t1.csv vectorstats/0/outabs_effect_t1.csv -frac 1e-6
testing_diff_matrix tmpoutabs_effect_t2.csv vectorstats/0/outabs_effect_t2.csv -frac 1e-6
testing_diff_matrix tmpoutabs_effect_t3.csv vectorstats/0/outabs_effect_t3.csv -frac 1e-6
testing_diff_matrix tmpoutbetas.csv vectorstats/0/outbetas.csv -frac 1e-6
testing_diff_matrix tmpoutstd_dev.csv vectorstats/0/outstd_dev.csv -frac 1e-6
testing_diff_matrix tmpoutstd_effect_t1.csv vectorstats/0/outstd_effect_t1.csv -frac 1e-6
testing_diff_matrix tmpoutstd_effect_t2.csv vectorstats/0/outstd_effect_t2.csv -frac 1e-6
testing_diff_matrix tmpoutstd_effect_t3.csv vectorstats/0/outstd_effect_t3.csv -frac 1e-6
testing_diff_matrix tmpouttvalue_t1.csv vectorstats/0/outtvalue_t1.csv -frac 1e-6
testing_diff_matrix tmpouttvalue_t2.csv vectorstats/0/outtvalue_t2.csv -frac 1e-6
testing_diff_matrix tmpouttvalue_t3.csv vectorstats/0/outtvalue_t3.csv -frac 1e-6
vectorstats/test0.py
