#!/bin/bash
# Verify the export of unmodulated tensor eigenvectors
# For each of the three eigenvectors,
#   simultaneously ensure that:
#   - The result corresponds to the eigenvector computed
#     using a prior version of the software
#     (ignoring any difference in sign)
#   - The squared norm of the eigenvector is 1.0
tensor2metric tensor2metric/dt.mif -num 1 -modulate none -vector - | \
mrcalc - tensor2metric/eigvec1.mif -multiply - | \
mrmath -axis 3 - sum - | \
mrcalc - -abs - | \
testing_diff_image - tensor2metric/ones.mif -frac 1e-5

tensor2metric tensor2metric/dt.mif -num 2 -modulate none -vector - | \
mrcalc - tensor2metric/eigvec2.mif -multiply - | \
mrmath -axis 3 - sum - | \
mrcalc - -abs - | \
testing_diff_image - tensor2metric/ones.mif -frac 1e-5

tensor2metric tensor2metric/dt.mif -num 3 -modulate none -vector - | \
mrcalc - tensor2metric/eigvec3.mif -multiply - | \
mrmath -axis 3 - sum - | \
mrcalc - -abs - | \
testing_diff_image - tensor2metric/ones.mif -frac 1e-5
