#!/bin/bash
# Verify calculation of ann Apparent Diffusion Coefficient (ADC) image
# Result is compared to that generated using a prior software version
tensor2metric tensor2metric/dt.mif -adc - | \
testing_diff_image - tensor2metric/adc.mif -frac 1e-5
