#!/bin/bash
# Verifies that the SIFT method achieves what the expected outcome should be
#   given knowledge of the underlying fibre structure
#   and the manifestation of a known reconstruction bias
# Given the difference in lengths of the two bundles,
#   and the use of homogeneous seeding in generation of the initial tractogram,
#   the longer bundle presents a greater seeding volume and therefore contains more streamlines.
#   After SIFT, the number of streamlines in each bundle should be comparable.
rm -rf tmp/
tcksift SIFT_phantom/tracks.tck SIFT_phantom/fods.mif tmp.tck -output_debug tmp/ -csv tmp.csv -force
tckmap tmp.tck -template SIFT_phantom/mask.mif -precise tmp.mif -force
mrstats tmp.mif -mask SIFT_phantom/upper.mif -output mean > tmp1.txt
mrstats tmp.mif -mask SIFT_phantom/lower.mif -output mean > tmp2.txt
testing_diff_matrix tmp1.txt tmp2.txt -abs 10
