#!/bin/bash
# REFERENCE: generate with: tckmap tracks.tck -template dwi.mif -contrast scalar_map -image dwi_mean.mif tckmap/tdi_scalar_map.mif.gz -force
# Verify the "scalar_map" contrast type for tckmap,
#   which assigns voxel values using a scalar image sampled along each streamline
# The dwi_mean.mif image is used as the scalar map
# Output is compared to that generated using a prior version of the software;
#   a tolerance of 1e-4 absolute is permitted to account for platform differences
tckmap tracks.tck -template dwi.mif -contrast scalar_map -image dwi_mean.mif - | \
testing_diff_image - tckmap/tdi_scalar_map.mif.gz -abs 1e-4
