#!/bin/bash
# Verify command operation when the -bottom command-line option is specified
#   such that the output mask contains the 20 lowest-valued voxels
mrthreshold dwi_mean.mif - -bottom 20 | \
testing_diff_image - mrthreshold/3d_bottom20.mif
