#!/bin/bash
# Verify conversion from deformation field to displacement field
# The warp.mif file is a 4D deformation field;
#   converting it to a displacement field and then back should recover the original
# Ensure that round-trip conversion matches the input to floating-point precision
# REFERENCE: This test does not require pre-generated reference data

warpconvert warp.mif deformation2displacement tmp_disp.mif -force
warpconvert tmp_disp.mif displacement2deformation tmp_def.mif -force
testing_diff_image tmp_def.mif warp.mif -abs 1e-4
