#!/bin/bash
# Verify conversion from deformation field to displacement field
# Ensure that output matches that generated using a prior software version

warpconvert deformation2displacement warp.mif - | \
testing_diff_image - warpconvert/displacement.mif -abs 1e-5
