#!/bin/bash
# Verify conversion from displacement field to deformation field
# Converting the displacement field originally computed from deformation field warp.mif
#   back to a deformation field should recover the original deformation field

warpconvert warpconvert/displacement.mif displacement2deformation - | \
testing_diff_image - warp.mif -abs 1e-5
