#!/bin/bash
# Basic test of command where the input non-linear transformation is a unit warp
# The output of the command however is not compared to the niput tractogram,
#   as one might expect given that a unit warp should not deform streamlines;
#   this is because the input streamlines reach the outer edge of the image FoV,
#   and therefore the unit warp cannot be interpolated beyond that edge
# THe output is therefore instead compared to that generated using a prior software version
tcktransform tracks.tck unit_warp.mif tmp.tck -force
testing_diff_tck tmp.tck tcktransform/out.tck -distance 1e-4
