#!/bin/bash
# Verify operation of "dwibiascorrect ants" algorithm
#   where image paths include whitespace characters

ln -s BIDS/sub-01/dwi/sub-01_dwi.nii.gz "tmp in.nii.gz"
ln -s BIDS/sub-01/dwi/sub-01_dwi.bvec "tmp in.bvec"
ln -s BIDS/sub-01/dwi/sub-01_dwi.bval "tmp in.bval"
ln -s BIDS/sub-01/dwi/sub-01_brainmask.nii.gz "tmp mask.nii.gz"

dwibiascorrect ants "tmp in.nii.gz" "tmp out.mif" -force \
-fslgrad "tmp in.bvec" "tmp in.bval" \
-mask "tmp mask.nii.gz" \
-bias "tmp bias.mif"

testing_diff_header "tmp out.mif" dwibiascorrect/ants/default_out.mif.gz
testing_diff_header "tmp bias.mif" dwibiascorrect/ants/default_bias.mif.gz
