#!/bin/bash
# Test the "pad" operation,
#   with padding applied exclusively to one axis,
#   and different amounts of padding applied to the lower and upper ends of the image along that axis
# Outcome is validated against that generated using a prior software version
mrgrid dwi.mif pad -axis 0 1,2 - | \
testing_diff_image - mrpad/out2.mif
