#!/bin/bash
# Basic test verifying default operation of command
# Ensure that output matches that generated using a prior software version
dwi2tensor dwi.mif - | \
testing_diff_image - dwi2tensor/out.mif -frac 1e-5

