#!/bin/bash
# Ensure that the ACT -backtrack capability executes
#   (no validation of "correct" operation is performed; only that execution completes)
tckgen SIFT_phantom/fods.mif \
    -algo ifod1 \
    -seed_voxels SIFT_phantom/mask.mif \
    -select 100 \
    -act SIFT_phantom/5tt.mif \
    -backtrack \
    tmp.tck -force
