#!/bin/bash
# Verify that tckgen can write TRX output with float16 positions via -trx_float16
# Both float32 (default) and float16 files are generated and each reports 100 streamlines
tckgen SIFT_phantom/fods.mif -algo ifod2 \
    -seed_image SIFT_phantom/mask.mif -mask SIFT_phantom/mask.mif \
    -minlength 4 -select 100 tmp_f32.trx -force
tckgen SIFT_phantom/fods.mif -algo ifod2 \
    -seed_image SIFT_phantom/mask.mif -mask SIFT_phantom/mask.mif \
    -minlength 4 -select 100 tmp_f16.trx -trx_float16 -force
tckinfo tmp_f32.trx | grep -q "TRX streamlines:.*100"
tckinfo tmp_f16.trx | grep -q "TRX streamlines:.*100"
# float16 file should be smaller than float32 (positions array is half the size)
[ $(wc -c < tmp_f16.trx) -lt $(wc -c < tmp_f32.trx) ]
