#!/bin/bash
# Verify operation of "msmt_csd" algorithm when a user-specified mask is provided
# Use conventional three macroscopic tissue types
# Ensure that outputs match those generated using a prior software version
dwi2fod msmt_csd dwi2fod/msmt/dwi.mif \
-mask dwi2fod/msmt/mask.mif \
dwi2fod/msmt/wm.txt tmp_wm_m.mif \
dwi2fod/msmt/gm.txt tmp_gm_m.mif \
dwi2fod/msmt/csf.txt tmp_csf_m.mif

testing_diff_image tmp_wm_m.mif dwi2fod/msmt/wm_masked.mif -abs 1e-5
testing_diff_image tmp_gm_m.mif dwi2fod/msmt/gm_masked.mif -abs 1e-5
testing_diff_image tmp_csf_m.mif dwi2fod/msmt/csf_masked.mif -abs 1e-5
