#!/bin/bash
# Verify operation of "msmt_csd" algorithm,
#   under default operation,
#   with conventional three macroscopic tissue responses
# Compare outputs to those generated using a prior software version
dwi2fod msmt_csd dwi2fod/msmt_csd/dwi.mif \
    dwi2fod/msmt_csd/wm.txt tmp_wm.mif \
    dwi2fod/msmt_csd/gm.txt tmp_gm.mif \
    dwi2fod/msmt_csd/csf.txt tmp_csf.mif \
    -predicted_signal tmp_predicted.mif \
    -force

testing_diff_image tmp_wm.mif dwi2fod/msmt_csd/wm.mif -abs 1e-5
testing_diff_image tmp_gm.mif dwi2fod/msmt_csd/gm.mif -abs 1e-5
testing_diff_image tmp_csf.mif dwi2fod/msmt_csd/csf.mif -abs 1e-5
testing_diff_image tmp_predicted.mif dwi2fod/msmt_csd/predicted.mif -voxel 1e-5
