#!/bin/bash
# Verify operation of "msmt_csd" algorithm when a user-specified mask is provided
# Use conventional three macroscopic tissue types
# Ensure that outputs match those generated using a prior software version
dwi2fod msmt_csd dwi2fod/msmt_csd/dwi.mif \
    -mask dwi2fod/msmt_csd/mask.mif \
    dwi2fod/msmt_csd/wm.txt tmp_wm.mif \
    dwi2fod/msmt_csd/gm.txt tmp_gm.mif \
    dwi2fod/msmt_csd/csf.txt tmp_csf.mif \
    -force

testing_diff_image tmp_wm.mif dwi2fod/msmt_csd/wm_masked.mif -abs 1e-5
testing_diff_image tmp_gm.mif dwi2fod/msmt_csd/gm_masked.mif -abs 1e-5
testing_diff_image tmp_csf.mif dwi2fod/msmt_csd/csf_masked.mif -abs 1e-5
