#!/bin/bash
# Ensure successful execution of the sd_stream algorithm
#   (no verification of the generated data is performed)
tckgen SIFT_phantom/fods.mif -algo sd_stream \
-seed_image SIFT_phantom/mask.mif -mask SIFT_phantom/mask.mif -minlength 4 -select 100 -seed_direction 1,0,0 tmp.tck -force
