#!/bin/bash
# Basic test of default operation with no command-line options
# Cannot compare directly to a pre-generated output due to stochasticity of command;
#   instead ensure that statistical properties of generated direction set
#   is comparable to that of a previously generated set

dirgen 20 tmp.txt -force

dirstat tmp.txt | \
grep 'nearest-neighbour angles:' | \
head -n 1 | \
awk '{ print $5$8 "," $10 }' | \
tr ',' ' ' > tmp_stats.txt

testing_diff_matrix tmp_stats.txt dirgen/stats_20.txt -abs 0.1
