#!/bin/bash
# Ensure that when the "Exp1" estimator is used for voxel-wise rank estimation,
#   the outputs match that generated using a prior software version
# Both the denoised DWI data, and the estimated noise level, are checked
dwidenoise dwi.mif tmp-denoised-exp1.mif -noise tmp-noise-exp1.mif -estimator Exp1
testing_diff_image tmp-denoised-exp1.mif dwidenoise/denoised_exp1.mif -voxel 1e-3
testing_diff_image tmp-noise-exp1.mif dwidenoise/noise_exp1.mif \
-image $(mrcalc dwi_mean.mif -abs 1e-4 -mult - | mrfilter - smooth -)
