#!/bin/bash
# Ensure that the map encoding the estimated noise level is approximately equivalent
#   to that generated using a prior software version
#   when command is run using default parameters
# The tolerance applied to the noise level comparison is modulated
#   based on the mean DWI intensity
dwidenoise dwi.mif -noise - tmp-denoised.mif -force | \
testing_diff_image - dwidenoise/noise.mif \
-image $(mrcalc dwi_mean.mif -abs 2e-4 -mult - | mrfilter - smooth -)
