#!/bin/bash
# Ensure that when the -rpe_header command-line option is utilised
#   in conjunction with the -se_epi option providing paired b=0 volumes with reversed phase encoding,
#   the script figures out how to process the data and completes successfully

mrconvert BIDS/sub-04/dwi/sub-04_dwi.nii.gz tmp-sub-04_dwi.mif -force \
-fslgrad BIDS/sub-04/dwi/sub-04_dwi.bvec BIDS/sub-04/dwi/sub-04_dwi.bval \
-json_import BIDS/sub-04/dwi/sub-04_dwi.json \
-strides 0,0,0,1

mrconvert BIDS/sub-04/fmap/sub-04_dir-1_epi.nii.gz tmp-sub-04_dir-1_epi.mif -force \
-json_import BIDS/sub-04/fmap/sub-04_dir-1_epi.json
mrconvert BIDS/sub-04/fmap/sub-04_dir-2_epi.nii.gz tmp-sub-04_dir-2_epi.mif -force \
-json_import BIDS/sub-04/fmap/sub-04_dir-2_epi.json
mrcat tmp-sub-04_dir-1_epi.mif tmp-sub-04_dir-2_epi.mif tmp-sub-04_dir-all_epi.mif -axis 3 -force

dwifslpreproc tmp-sub-04_dwi.mif tmp.mif -rpe_header -force \
-se_epi tmp-sub-04_dir-all_epi.mif -force

testing_diff_header tmp.mif dwifslpreproc/rpepair_default.mif.gz
