#!/bin/bash
# Verify operation of command when the output maximal spherical harmonic degree is overridden
# Ensure that output matches that generated using a prior software version
fixel2sh fixel_image/afd.mif -lmax 4 - | \
testing_diff_image - fixel2sh/out1.mif -voxel 1e-5
