#!/bin/bash
# Verify successful execution of "dwi2response tax"
#   where the maximal spherical harmonc degree of the response function
#   is specified using the -lmax option
# Ensure that outputs match those generated
#   using a prior version of the software

dwi2response tax BIDS/sub-01/dwi/sub-01_dwi.nii.gz tmp_out.txt -force \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval \
-voxels tmp_voxels.mif \
-lmax 6

testing_diff_matrix tmp_out.txt dwi2response/tax/lmax.txt -abs 1e-2
testing_diff_image tmp_voxels.mif dwi2response/tax/lmax.mif.gz
