#!/bin/bash
# Verify successful execution of "dwi2response tournier"
#   where image piping is utilised

mrconvert BIDS/sub-01/dwi/sub-01_dwi.nii.gz - \
-strides 0,0,0,1 \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval | \
dwi2response tournier - tmp.txt -force \
-voxels - \
-number 20 \
-iter_voxels 200 | \
testing_diff_image - dwi2response/tournier/default.mif.gz

