#!/bin/bash
# Ensure that input image can undergo trilinear interpolation

rm -f tmp.txt
! ( mrconvert 5ttedit/in.mif -coord 0 0 - | \
    5ttvalidate - > tmp.txt 2>&1 )
cat tmp.txt
grep "Needs to be non\\-unity in all three spatial dimensions" tmp.txt
