#!/bin/bash
# Verify "lower_triangular" operation, when input data are upper triangular
# Input:
# [[1, 2, 3],
#  [0, 4, 5],
#  [0, 0, 6]]
# Output:
# [[1, 0, 0],
#  [2, 4, 0],
#  [3, 5, 6]]
printf $"1 2 3\n0 4 5\n0 0 6\n" > tmp.txt
connectomeedit -force tmp.txt lower_triangular tmp1.txt
printf $"1 0 0\n2 4 0\n3 5 6\n" > tmp2.txt
testing_diff_matrix tmp1.txt tmp2.txt
