#!/bin/bash
# Verify the "to_symmetric" operation, when input are symmetric
# Input:
# [[1, 2, 3],
#  [2, 4, 5],
#  [3, 5, 6]]
# Output: Same as input
printf $"1 2 3\n2 4 5\n3 5 6\n" > tmp.txt
connectomeedit -force tmp.txt to_symmetric tmp1.txt
testing_diff_matrix tmp1.txt tmp.txt
