#!/bin/bash
# Verify command operation when using:
# - A *4D* input image
# - *Interpolation* is used
#   (Linear interpolation is used merely as the exemplar)
# - A track-wise statistic *is* used
#   (the mean is chosen here merely as an exemplar)
# Outcome is verified against that generated using a prior software version
mrcat tcksample/fa.mif tcksample/adc.mif -axis 3 - | \
    tcksample tracks.tck - tmp.csv -stat_tck mean -force

testing_diff_matrix tmp.csv tcksample/input4d_interplinear_statmean.csv -frac 1e-5
