#!/bin/bash
# Verify command operation when using:
# - A *3D* input image
# - *Precise* streamline-to-voxel mapping mechanism
# - A track-wise statistic *is* used
#   (mean is used merely as the exemplar)
# Outcome is verified against that generated using a prior software version
tcksample tracks.tck tcksample/fa.mif tmp.csv -precise -stat_tck mean -force
testing_diff_matrix tmp.csv tcksample/input3d_precise_statmean.csv -frac 1e-5
