#!/bin/bash
# Verify command operation when using:
# - A *4D* input image
# - The *precise* streamline-to-voxel mapping mechanism is used
# - The "-use_tdi_fraction" option is used
# Outcome is verified against that generated using a prior software version
# More lenient threshold found to be necessary to pass tests on MacOS
mrcat tcksample/fa.mif tcksample/adc.mif -axis 3 - | \
    tcksample tracks.tck - tmp.csv -stat_tck mean -precise -use_tdi_fraction -force

testing_diff_matrix tmp.csv tcksample/input4d_precise_tdifrac_statmean.csv -frac 2e-5
