#!/bin/bash
# Verify command operation when the median track-wise statistic is requested
# Outcome is verified against that generated using a prior software version
tcksample tracks.tck tcksample/fa.mif tmp.csv -stat_tck median -force
testing_diff_matrix tmp.csv tcksample/median.csv -frac 1e-5
