#!/bin/bash
# Verify command operation when the maximum track-wise statistic is requested
# Outcome is compared to that generated using a prior software version
tcksample tracks.tck tcksample/fa.mif tmp.csv -stat_tck max -force
testing_diff_matrix tmp.csv tcksample/max.csv -frac 1e-5
