/* Copyright (c) 2008-2026 the MRtrix3 contributors.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * Covered Software is provided under this License on an "as is"
 * basis, without warranty of any kind, either expressed, implied, or
 * statutory, including, without limitation, warranties that the
 * Covered Software is free of defects, merchantable, fit for a
 * particular purpose or non-infringing.
 * See the Mozilla Public License v. 2.0 for more details.
 *
 * For more details, see http://www.mrtrix.org/.
 */

#pragma once

#include <cstddef>
#include <filesystem>
#include <string>
#include <system_error>
#include <variant>
#include <vector>

#include "app.h"
#include "datatype.h"
#include "exception.h"
#include "progressbar.h"
#include "raw.h"
#include "signal_handler.h"

#include "dwi/tractography/field_registry.h"
#include "dwi/tractography/formats/base.h"
#include "dwi/tractography/formats/list.h"
#include "dwi/tractography/properties.h"
#include "dwi/tractography/sidecar.h"
#include "dwi/tractography/sidecar_export.h"
#include "dwi/tractography/sidecar_value.h"
#include "dwi/tractography/tractogram.h"
#include "dwi/tractography/tractogram_item.h"

namespace MR::DWI::Tractography {

//! \brief Ordered queue sink that writes each composite item to an output tractogram.
/*! The sink for the create / rewrite destinations of embed_sidecar_field(): the
 * output tractogram (the input streamlines plus the freshly-computed field already
 * slotted into the item by the producing worker) is generated by the embedding
 * queue itself, so the input is not looped a second time. */
template <class ValueType = float> class EmbedWriterSink {
public:
  EmbedWriterSink(Tractogram<ValueType> &output, const size_t num_tracks)
      : output(output), progress("writing output tractogram with embedded field", num_tracks) {}
  EmbedWriterSink(const EmbedWriterSink &) = delete;
  bool operator()(const TractogramItem<ValueType> &item) {
    output.write(item);
    ++progress;
    return true;
  }

private:
  Tractogram<ValueType> &output;
  ProgressBar progress;
};

//! \brief Ordered queue sink that accumulates the embedded field then appends it to an
//!   existing dataset in place (no streamline rewrite); call finalise() when done.
/*! The sink for the in-place AppendInPlace destination of embed_sidecar_field():
 * the producing worker has already slotted the computed field into each item at
 * \a ordinal, so this sink merely serialises that field's bytes in streamline order
 * and hands them to the handler as a new sidecar member at finalisation. */
template <class ValueType = float> class EmbedAppendSink {
public:
  EmbedAppendSink(const Formats::Base &handler,
                  std::filesystem::path dataset,
                  FieldDescriptor descriptor,
                  const size_t ordinal,
                  const size_t num_tracks)
      : handler(handler),
        dataset(std::move(dataset)),
        descriptor(std::move(descriptor)),
        ordinal(ordinal),
        progress("appending sidecar field to dataset", num_tracks) {}
  EmbedAppendSink(const EmbedAppendSink &) = delete;

  bool operator()(const TractogramItem<ValueType> &item) {
    if (descriptor.role == FieldRole::DPV) {
      const auto &value = std::get<VectorOrMatrix<ValueType>>(item.dpv[ordinal]);
      append_floats(value.data(), static_cast<size_t>(value.size()));
    } else {
      const auto &value = std::get<ScalarOrVector<ValueType>>(item.dps[ordinal]);
      append_floats(value.data(), static_cast<size_t>(value.size()));
    }
    ++progress;
    return true;
  }

  //! \brief append the accumulated field bytes to the dataset as a new member.
  void finalise() { handler.append_sidecar(dataset, descriptor, bytes); }

private:
  const Formats::Base &handler;
  const std::filesystem::path dataset;
  const FieldDescriptor descriptor;
  const size_t ordinal;
  std::vector<std::byte> bytes;
  ProgressBar progress;

  void append_floats(const ValueType *const data, const size_t count) {
    const size_t offset = bytes.size();
    bytes.resize(offset + count * sizeof(float));
    for (size_t i = 0; i != count; ++i)
      Raw::store_LE<float>(static_cast<float>(data[i]), bytes.data() + offset + i * sizeof(float));
  }
};

//! \brief Embed a freshly-computed per-vertex / per-streamline field into a
//!   tractography dataset named by a qualified "DATASET::NAME" reference (§2.7).
/*! The single orchestration shared by every command that computes one sidecar
 * field per streamline (a per-streamline statistic) or per vertex (a per-vertex
 * sampling) and embeds it into a tractogram dataset. The producing command
 * supplies \a run_queue, a callable invoked exactly once as
 * \c run_queue(sink,ordinal): it must run its own thread queue, reading from the
 * already-opened \a input, slotting the computed field into each item's dpv/dps
 * payload at the assigned \a ordinal, and forwarding each item to \a sink. The
 * sink type is deduced (EmbedWriterSink for create/rewrite, EmbedAppendSink for
 * in-place append), so the same \a run_queue lambda serves all three destinations.
 *
 * The destination form is selected from the recognised format's capabilities:
 *   - the destination DOES NOT EXIST: a fresh copy of \a input carrying the new
 *     field is generated within the embedding queue (no second pass);
 *   - the destination EXISTS and the format can append a sidecar member in place
 *     (a TRX directory or uncompressed archive): the field is written as a new
 *     member with no rewrite of the streamline data; "-force" is required only if
 *     a field of this name is already present;
 *   - the destination EXISTS and the format must be rewritten to add a field
 *     (".trk", a compressed TRX archive): "-force" is required, and the augmented
 *     dataset is written to a sibling scratch file then atomically moved over the
 *     destination.
 *
 * \pre \a reference.dataset is recognised by a tractography handler (the caller
 * checks Formats::get_handler() != nullptr so it can treat a bare path as a
 * standalone file with command-specific phrasing). The reference must be qualified
 * ("DATASET::NAME"); a bare tractography path is rejected here, since embedding
 * requires an explicit field name. \a role selects the per-vertex (DPV) or
 * per-streamline (DPS) field shape and \a columns its column count (1 for a
 * scalar field, the number of metrics for a multi-column dps field). */
template <class ValueType, class RunQueue>
void embed_sidecar_field(const SidecarReference &reference,
                         Tractogram<ValueType> &input,
                         Properties &properties,
                         const FieldRole role,
                         const size_t columns,
                         const size_t num_tracks,
                         RunQueue &&run_queue) {
  const Formats::Base *const handler = Formats::get_handler(reference.dataset);
  assert(handler != nullptr);

  if (!reference.is_qualified())
    throw Exception("to embed data into a tractogram dataset \"" + reference.dataset.string() + "\"," +
                    " name the field with the \"DATASET::NAME\" form");
  if (handler->capabilities.sidecar_data == Formats::SidecarData::Unsupported)
    throw Exception("output tractography format \"" + handler->description + "\"" +
                    " cannot carry per-streamline / per-vertex sidecar data," +
                    " so the data cannot be embedded into \"" + reference.dataset.string() + "\"");

  const std::string field_name = *reference.name;

  const SidecarDestination destination = classify_sidecar_destination(*handler, reference.dataset);

  if (destination == SidecarDestination::AppendInPlace) {
    const size_t ordinal = (role == FieldRole::DPV) ? input.fields().dpv_count() : input.fields().dps_count();
    // The new member appends without rewriting the streamline data; "-force" is
    //   required only if a field of this name is already present in the dataset.
    {
      Properties existing_properties;
      auto existing = Tractogram<ValueType>::open(reference.dataset, existing_properties);
      if (existing.fields().ordinal(field_name, role).has_value())
        App::check_overwrite(reference.dataset);
    }
    const FieldDescriptor descriptor{field_name, role, DataType::Float32, columns, FieldSource::Internal, ordinal};
    EmbedAppendSink<ValueType> sink(*handler, reference.dataset, descriptor, ordinal, num_tracks);
    run_queue(sink, ordinal);
    sink.finalise();
    return;
  }

  // CreateDataset / RewriteDataset: generate the output tractogram (input streamlines
  //   plus the new field) within the embedding queue. A missing dataset is written
  //   directly; an existing rewrite-only dataset ("-force" required) is written to a
  //   sibling scratch file then atomically moved over the destination.
  const bool rewrite = destination == SidecarDestination::RewriteDataset;
  if (rewrite)
    App::check_overwrite(reference.dataset);
  const std::filesystem::path out_path = rewrite ? make_sibling_path(reference.dataset) : reference.dataset;

  FieldRegistry registry = input.fields();
  if (registry.ordinal(field_name, role).has_value())
    throw Exception("input tractogram already carries a field named \"" + field_name + "\"");
  const size_t ordinal = registry.add({field_name, role, DataType::Float32, columns, FieldSource::Internal, 0});

  if (rewrite)
    SignalHandler::mark_file_for_deletion(out_path);
  try {
    {
      auto output = Tractogram<ValueType>::create(out_path, properties, registry);
      EmbedWriterSink<ValueType> sink(output, num_tracks);
      run_queue(sink, ordinal);
    } // the output Tractogram is finalised (written) here, before any rename
    if (rewrite) {
      std::filesystem::rename(out_path, reference.dataset);
      SignalHandler::unmark_file_for_deletion(out_path);
    }
  } catch (...) {
    if (rewrite) {
      std::error_code ec;
      std::filesystem::remove(out_path, ec);
    }
    throw;
  }
}

} // namespace MR::DWI::Tractography
