#!/bin/bash
# Multiple tests for the C++ binary command-line interface

# Test using all options at once
mkdir -p tmp-dirin/ && touch tmp-filein.txt && touch tmp-tracksin.tck && testing_cpp_cli -flag -text my_text -choice One -bool false -int_unbound 0 -int_nonneg 1 -int_bound 50 -float_unbound 0.0 -float_nonneg 1.0 -float_bound 0.5 -int_seq 1,2,3 -float_seq 0.1,0.2,0.3 -dir_in tmp-dirin/ -dir_out tmp-dirout/ -file_in tmp-filein.txt -file_out tmp-fileout.txt -tracks_in tmp-tracksin.tck -tracks_out tmp-tracksout.tck -various my_various && rm -rf tmp-dirin/ && rm -f tmp-filein.txt && rm -f tmp-tracksin.tck

# Run previous with different option/argument orders
mkdir -p tmp-dirin/ && touch tmp-filein.txt && touch tmp-tracksin.tck && testing_cpp_cli -text my_text -choice One -bool false -int_unbound 0 -int_nonneg 1 -int_bound 50 -float_unbound 0.0 -float_nonneg 1.0 -float_bound 0.5 -int_seq 1,2,3 -float_seq 0.1,0.2,0.3 -dir_in tmp-dirin/ -dir_out tmp-dirout/ -file_in tmp-filein.txt -file_out tmp-fileout.txt -tracks_in tmp-tracksin.tck -tracks_out tmp-tracksout.tck -various my_various -flag && rm -rf tmp-dirin/ && rm -f tmp-filein.txt && rm -f tmp-tracksin.tck
mkdir -p tmp-dirin/ && touch tmp-filein.txt && touch tmp-tracksin.tck && testing_cpp_cli -choice One -bool false -int_unbound 0 -int_nonneg 1 -int_bound 50 -float_unbound 0.0 -float_nonneg 1.0 -float_bound 0.5 -int_seq 1,2,3 -float_seq 0.1,0.2,0.3 -dir_in tmp-dirin/ -dir_out tmp-dirout/ -file_in tmp-filein.txt -file_out tmp-fileout.txt -tracks_in tmp-tracksin.tck -tracks_out tmp-tracksout.tck -various my_various -flag -text my_text && rm -rf tmp-dirin/ && rm -f tmp-filein.txt && rm -f tmp-tracksin.tck
mkdir -p tmp-dirin/ && touch tmp-filein.txt && touch tmp-tracksin.tck && testing_cpp_cli -bool false -int_unbound 0 -int_nonneg 1 -int_bound 50 -float_unbound 0.0 -float_nonneg 1.0 -float_bound 0.5 -int_seq 1,2,3 -float_seq 0.1,0.2,0.3 -dir_in tmp-dirin/ -dir_out tmp-dirout/ -file_in tmp-filein.txt -file_out tmp-fileout.txt -tracks_in tmp-tracksin.tck -tracks_out tmp-tracksout.tck -various my_various -flag -text my_text -choice One && rm -rf tmp-dirin/ && rm -f tmp-filein.txt && rm -f tmp-tracksin.tck

# No arguments are supported
! testing_cpp_cli random_arg

# Test export of interface to various file formats
testing_cpp_cli -help | tail -n +3 > tmp.txt && diff -a --strip-trailing-cr tmp.txt cpp_cli/help.txt && rm -f tmp.txt
testing_cpp_cli __print_full_usage__ > tmp.txt && diff -a --strip-trailing-cr tmp.txt cpp_cli/full_usage.txt && rm -f tmp.txt
testing_cpp_cli __print_usage_markdown__ > tmp.md && diff -a --strip-trailing-cr tmp.md cpp_cli/markdown.md && rm -f tmp.md
testing_cpp_cli __print_usage_rst__ > tmp.rst && diff -a --strip-trailing-cr tmp.rst cpp_cli/restructured_text.rst && rm -f tmp.rst

# Test suitable handling of valid and invalid inputs to various argument types
testing_cpp_cli -bool false
testing_cpp_cli -bool False
testing_cpp_cli -bool FALSE
testing_cpp_cli -bool true
testing_cpp_cli -bool True
testing_cpp_cli -bool TRUE
testing_cpp_cli -bool 0
testing_cpp_cli -bool 1
testing_cpp_cli -bool 2
! testing_cpp_cli -bool NotABool
! testing_cpp_cli -int_unbound 0.1
! testing_cpp_cli -int_unbound NotAnInt
! testing_cpp_cli -int_nonneg -1
! testing_cpp_cli -int_bound 101
! testing_cpp_cli -float_unbound NotAFloat
! testing_cpp_cli -float_nonneg -0.1
! testing_cpp_cli -float_bound 1.1
! testing_cpp_cli -int_seq 0.1,0.2,0.3
! testing_cpp_cli -int_seq Not,An,Int,Seq
! testing_cpp_cli -float_seq Not,A,Float,Seq

# Options requiring arguments should fail if no argument is provided
! testing_cpp_cli -choice
! testing_cpp_cli -text
! testing_cpp_cli -bool
! testing_cpp_cli -int_unbound
! testing_cpp_cli -int_nonneg
! testing_cpp_cli -int_bound
! testing_cpp_cli -float_unbound
! testing_cpp_cli -float_nonneg
! testing_cpp_cli -float_bound
! testing_cpp_cli -int_seq
! testing_cpp_cli -float_seq
! testing_cpp_cli -file_in
! testing_cpp_cli -file_out
! testing_cpp_cli -dir_in
! testing_cpp_cli -dir_out
! testing_cpp_cli -tracks_in
! testing_cpp_cli -tracks_out
! testing_cpp_cli -various
! testing_cpp_cli -nargs_two
! testing_cpp_cli -nargs_two first

# Unsupported options should fail
! testing_cpp_cli -unsupported_option
! testing_cpp_cli -2244223

# Test handling of various dash-like characters
testing_cpp_cli —bool false # Em dash
testing_cpp_cli –bool false # En dash
testing_cpp_cli -bool false # Hyphen

# Test interfaces relating to filesystem paths:
# - Make sure that command fails if expected input is not present
# - Make sure that existing outputs either succeed or fail depending on the presence of the -force option
rm -rf tmp-dirin/ && ! testing_cpp_cli -dir_in tmp-dirin/
trap "rm -rf tmp-dirout/" EXIT; mkdir -p tmp-dirout/ && ! testing_cpp_cli -dir_out tmp-dirout/
trap "rm -rf tmp-dirout/" EXIT; mkdir -p tmp-dirout/ && testing_cpp_cli -dir_out tmp-dirout/ -force
rm -f tmp-filein.txt && ! testing_cpp_cli -file_in tmp-filein.txt
trap "rm -f tmp-fileout.txt" EXIT; touch tmp-fileout.txt && ! testing_cpp_cli -file_out tmp-fileout.txt
trap "rm -f tmp-fileout.txt" EXIT; touch tmp-fileout.txt && testing_cpp_cli -file_out tmp-fileout.txt -force
rm -f tmp-tracksin.tck && ! testing_cpp_cli -tracks_in tmp-tracksin.tck
trap "rm -f tmp-filein.txt" EXIT; touch tmp-filein.txt && ! testing_cpp_cli -tracks_in tmp-filein.txt
trap "rm -f tmp-tracksout.txt" EXIT; touch tmp-tracksout.tck && ! testing_cpp_cli -tracks_out tmp-tracksout.tck
trap "rm -f tmp-tracksout.txt" EXIT; touch tmp-tracksout.tck && testing_cpp_cli -tracks_out tmp-tracksout.tck -force

