#!/bin/bash
# Ensure that if one of the inputs to the dwicat command
#   is a 3D image rather than a 4D series,
#   the command still executes successfully

dwiextract BIDS/sub-01/dwi/sub-01_dwi.nii.gz tmp_b0_b1000.mif -force \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval \
-shell 0,1000

mrconvert tmp_b0_b1000.mif tmp_b0.mif -coord 3 0 -axes 0,1,2 -force

dwicat tmp_b0_b1000.mif tmp_b0.mif tmp.mif -force
