#!/bin/bash
# Verify non-linear warping of an FOD image including FOD reorientation
mrtransform fod.mif -warp rotatez_warp.mif -reorient_fod yes - | \
testing_diff_image - mrtransform/out9.mif.gz -voxel 0.001
