#!/bin/bash
# Verify basic operation of command
# Outcome is compared to that calculated using a prior software version
tsfdivide afd.tsf afd.tsf tmp.tsf -force
testing_diff_tsf tmp.tsf tsfdivide/out.tsf -frac 1e-5
