#!/bin/bash
# Verify inversion of a deformation field
# The unit_warp.mif is an identity deformation field;
#   inverting it should produce a result that is very close to itself
# Ensure that the inverted identity warp matches the original to floating-point precision

warpinvert unit_warp.mif - | \
testing_diff_image - unit_warp.mif -abs 1e-3
