#!/bin/bash
# Verify inversion of a unit deformation field converted to a displacement field
# Convert the unit (identity) deformation field to a displacement field,
#   invert it, then convert back to a deformation field;
#   the result should match the original identity warp

warpconvert deformation2displacement unit_warp.mif - | \
warpinvert - -displacement - | \
warpconvert displacement2deformation - - | \
testing_diff_image - unit_warp.mif -abs 1e-5
