#!/bin/bash
# Verify operation of the "mask2glass" command
#   where image piping is used
mrconvert BIDS/sub-01/dwi/sub-01_brainmask.nii.gz - | \
mask2glass - - | \
testing_diff_image - mask2glass/out.mif.gz
