#!/bin/bash
# Ensure that the dwigradcheck script completes successfully
#   with the use of piped images

# Input DWI is piped
mrconvert BIDS/sub-01/dwi/sub-01_dwi.nii.gz - \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval \
-strides 0,0,0,1 | \
dwigradcheck -

# Input brain mask is piped
mrconvert BIDS/sub-01/dwi/sub-01_brainmask.nii.gz - | \
dwigradcheck BIDS/sub-01/dwi/sub-01_dwi.nii.gz \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval \
-mask -
