#!/bin/bash
# Verify the diff metric computed in average scanner space
# Comparing an image with itself in average space should yield zero;
#   verify that the output is 0

RESULT=$(mrmetric dwi_mean.mif dwi_mean.mif -space average)
(( $(echo "$RESULT == 0" | bc) ))
