#!/bin/bash
# Verify the diff metric computed in average scanner space

transformcalc moving2template.txt half tmp_forwardhalf.txt -force
mrtransform moving.mif.gz -linear tmp_forwardhalf.txt tmp_moving.mif -force
transformcalc moving2template.txt invert tmp_template2moving.txt -force
transformcalc tmp_template2moving.txt half tmp_inversehalf.txt -force
mrtransform template.mif.gz -linear tmp_inversehalf.txt tmp_template.mif -force
rm -f tmp.txt
! mrmetric tmp_moving.mif tmp_template.mif -space voxel

mraverageheader tmp_moving.mif tmp_template.mif tmp_average.mif -force
mrgrid tmp_moving.mif regrid -template tmp_average.mif tmp_moving_regrid.mif -force
mrgrid tmp_template.mif regrid -template tmp_average.mif tmp_template_regrid.mif -force
mrmetric tmp_moving_regrid.mif tmp_template_regrid.mif -space voxel > tmp.txt
testing_diff_matrix tmp.txt mrmetric/diff_voxel.txt -frac 1e-5
