#!/bin/bash
# Verify the diff metric computed with a mask applied to both images
# Comparing an image with itself inside a mask should yield zero;
#   verify that the output is 0

RESULT=$(mrmetric dwi_mean.mif dwi_mean.mif -mask1 mask.mif -mask2 mask.mif)
(( $(echo "$RESULT == 0" | bc) ))
