#!/bin/bash
# Test successful execution for four subsets
#   where the -firstisfirst option is specified
# Cannot compare directly to a pre-generated output due to stochasticity of command

dirmerge 4 \
0 dirmerge/bzero_2.txt dirmerge/bzero_2.txt dirmerge/bzero_2.txt dirmerge/bzero_2.txt \
300 dirmerge/12_1of4.txt dirmerge/12_2of4.txt dirmerge/12_3of4.txt dirmerge/12_4of4.txt \
1000 dirmerge/24_1of4.txt dirmerge/24_2of4.txt dirmerge/24_3of4.txt dirmerge/24_4of4.txt \
3000 dirmerge/60_1of4.txt dirmerge/60_2of4.txt dirmerge/60_3of4.txt dirmerge/60_4of4.txt \
tmp.txt -force -firstisfirst
