#!/bin/bash
# Verify that use of the -scanner2voxel option produces a result
#   that is consistent with that produced by a prior software version
# The ASCII VTK format is used just for the sake of the comparison,
#   and is not crucial for the command functionality
tckconvert -ascii tracks.tck -scanner2voxel dwi.mif tmp.vtk -force
awk '/POINTS/{s=1;next}/LINES/{s=0}s' tmp.vtk > tmppoints1.txt
awk '/POINTS/{s=1;next}/LINES/{s=0}s' tckconvert/out1.vtk > tmppoints2.txt
awk '/LINES/,0' tmp.vtk > tmplines1.txt
awk '/LINES/,0' tckconvert/out1.vtk > tmplines2.txt
testing_diff_matrix tmppoints1.txt tmppoints2.txt -abs 1e-4
diff tmplines1.txt tmplines2.txt
