#!/bin/bash
# Test adding a data-per-streamline value to a TRX with float32 datatype
# Also tests writing an uncompressed TRX directory.
# There are 13 streamlines in gs.tck, so we need 13 values in dps.txt:
for n in {0..12}
do
   echo "${n}.0" >> dps.txt
done

# Test adding a data-per-streamline value to a TRX:
tckconvert gs.tck tmp_dps_float32.trx -trxdirectory -dps dps float32 dps.txt -force && [[ -f tmp_dps_float32.trx/dps/dps.float32 ]]