#!/bin/bash
# Test adding a data-per-streamline value to a TRX with float16 datatype
# Also tests writing an uncompressed TRX directory.
# There are 13 streamlines in gs.tck, so we need 13 values in tmp_dps.txt:
for n in {0..12}
do
   echo "${n}.0" >> tmp_dps.txt
done

tckconvert tckconvert/gs.tck tmp_dps_float16.trx -trxdirectory -dps dps float16 tmp_dps.txt -force && [[ -f tmp_dps_float16.trx/dps/dps.float16 ]]
