#!/bin/bash
# Verify basic read-write functionality of the PNG format
# Two tests are performed:
# - A grayscale image
# - An RGB image
echo -e "1 0 0 0\n0 1 0 0\n0 0 1 0\n" > tmp.txt
rm -f tmp-*.png

mrconvert mrconvert/in.mif tmp-gray[].png
mrcalc mrconvert/in.mif 0 -max - | \
mrtransform - -replace tmp.txt tmp-gray.mif -force
testing_diff_image tmp-gray[].png tmp-gray.mif

mrconvert unit_warp.mif tmp-rgb[].png -datatype uint8
mrcalc unit_warp.mif 0 -max -round - | \
mrtransform - -replace tmp.txt - | \
mrconvert - -vox 1,1,1 tmp-rgb.mif -force
testing_diff_image tmp-rgb[].png tmp-rgb.mif
