#!/bin/bash
# Verify that after manually manipulating the image strides,
#   the resulting image is nevertheless interpreted by MRtrix3 as being
#   identical to the input image
for STRIDES in "+1,+2,+3" "+1,+2,-3" "+1,-2,+3" "+1,-2,-3" "-1,+2,+3" "-1,+2,-3" "-1,-2,+3" "-1,-2,-3" \
               "+1,+3,+2" "+1,+3,-2" "+1,-3,+2" "+1,-3,-2" "-1,+3,+2" "-1,+3,-2" "-1,-3,+2" "-1,-3,-2" \
               "+2,+1,+3" "+2,+1,-3" "+2,-1,+3" "+2,-1,-3" "-2,+1,+3" "-2,+1,-3" "-2,-1,+3" "-2,-1,-3" \
               "+2,+3,+1" "+2,+3,-1" "+2,-3,+1" "+2,-3,-1" "-2,+3,+1" "-2,+3,-1" "-2,-3,+1" "-2,-3,-1" \
               "+3,+1,+2" "+3,+1,-2" "+3,-1,+2" "+3,-1,-2" "-3,+1,+2" "-3,+1,-2" "-3,-1,+2" "-3,-1,-2" \
               "+3,+2,+1" "+3,+2,-1" "+3,-2,+1" "+3,-2,-1" "-3,+2,+1" "-3,+2,-1" "-3,-2,+1" "-3,-2,-1"; do
    mrconvert mrconvert/in.mif -strides $STRIDES - | \
    testing_diff_image - mrconvert/in.mif
done
