# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '3.0.5.dev589+g9e2806609.d20230817'
__version_tuple__ = version_tuple = (3, 0, 5, 'dev589', 'g9e2806609.d20230817')
