#!/bin/bash
# REFERENCE: generate with: dwiextract dwi.mif -shells 3000 dwiextract/out_shells3000.mif -force
# Verify extraction of a specific shell by b-value using the -shells option
# Selecting b=3000 should yield only the diffusion-weighted volumes
# Outcome is compared against that generated using a prior software version
dwiextract dwi.mif -shells 3000 - | \
testing_diff_image - dwiextract/out_shells3000.mif
