#!/bin/bash
# REFERENCE: generate with: dwiextract dwi.mif -singleshell dwiextract/out_singleshell.mif -force
# Verify operation of the -singleshell option,
#   which forces extraction of a single non-b=0 shell including b=0 volumes
# Outcome is compared against that generated using a prior software version
dwiextract dwi.mif -singleshell - | \
testing_diff_image - dwiextract/out_singleshell.mif
