#!/bin/bash
# Evaluation of the operation of the "entropy" operation for the sh2metric command
#   when multiple SH images are provided as input
sh2metric dwi2fod/msmt_csd/wm.mif dwi2fod/msmt_csd/gm.mif dwi2fod/msmt_csd/csf.mif entropy - | \
    testing_diff_image - sh2metric/entropy_multiinput.mif -frac 0.1
