#!/bin/bash
# Ensures that the -axis option can be specified to control the axis along which concatenation is performed,
#   even in the scenario where that axis index is beyond the dimensionality of the input images
rm -f tmp-*.mif
mrconvert dwi.mif tmp-[].mif

mrcat tmp-[0:16].mif tmp-[17:33].mif tmp-[34:50].mif tmp-[51:67].mif - \
-axis 4 | \
testing_diff_image - mrcat/out.mif
