#!/bin/bash
# Evaluates the "smooth" filter when a 3-vector of standard deviation per axis is specified
#   (while this permits the definition of an anisotropic smoothing kernel,
#   the current test data utilised the same value for each spatial axis)
# Output is compared against that generated using a prior software version
mrfilter dwi.mif smooth -stdev 1.5,1.5,1.5 - | \
testing_diff_image - mrfilter/out2.mif -frac 1e-5
