#!/bin/bash
# Validate defulat operation with the "hot" colourmap
#   against a result generated with a prior software version
mrcolour dwi_mean.mif hot - | \
testing_diff_image - mrcolour/hot.mif -abs 1e-5
