#!/bin/bash
# vectorstats test 1
#
# Prior version where test data were generated dynamically:
# N=16 SNR=5 vectorstats/gen1.py
# vectorstats tmpsubjects.txt tmpdesign.csv tmpcontrast.csv tmpout/ -errors ise
# vectorstats/test1.py
# This is no longer used in order to prevent random CI failures
rm -rf tmpout/
vectorstats vectorstats/1_in/subjects.txt vectorstats/1_in/design.csv tmpout/ \
    -ttests vectorstats/1_in/contrast.csv \
    -errors ise

testing_diff_matrix tmpout/Zstat_t1.csv vectorstats/1_out/Zstat_t1.csv -frac 1e-6
testing_diff_matrix tmpout/Zstat_t2.csv vectorstats/1_out/Zstat_t2.csv -frac 1e-6
testing_diff_matrix tmpout/abs_effect_t1.csv vectorstats/1_out/abs_effect_t1.csv -frac 1e-6
testing_diff_matrix tmpout/abs_effect_t2.csv vectorstats/1_out/abs_effect_t2.csv -frac 1e-6
testing_diff_matrix tmpout/betas.csv vectorstats/1_out/betas.csv -frac 1e-6
testing_diff_matrix tmpout/std_dev.csv vectorstats/1_out/std_dev.csv -frac 1e-6
testing_diff_matrix tmpout/std_effect_t1.csv vectorstats/1_out/std_effect_t1.csv -frac 1e-6
testing_diff_matrix tmpout/std_effect_t2.csv vectorstats/1_out/std_effect_t2.csv -frac 1e-6
testing_diff_matrix tmpout/tvalue_t1.csv vectorstats/1_out/tvalue_t1.csv -frac 1e-6
testing_diff_matrix tmpout/tvalue_t2.csv vectorstats/1_out/tvalue_t2.csv -frac 1e-6

vectorstats/test1.py tmpout/
