#!/bin/bash
# vectorstats test 2
#
# Prior version where test data were generated dynamically:
# N=16 SNR=5 vectorstats/gen2.py
# vectorstats tmpsubjects.txt tmpdesign.csv tmpcontrast.csv tmpout/ -column tmpcolumn.txt -ftests tmpftests.csv
# vectorstats/test2.py
rm -rf tmpout/
vectorstats vectorstats/2_in/subjects.txt vectorstats/2_in/design.csv tmpout/ \
    -ttests vectorstats/2_in/contrast.csv \
    -column vectorstats/2_in/column.txt \
    -ftest vectorstats/2_in/ftest0.csv \
    -ftest vectorstats/2_in/ftest1.csv

testing_diff_matrix tmpout/Fvalue_F1.csv vectorstats/2_out/Fvalue_F1.csv -frac 1e-6
testing_diff_matrix tmpout/Fvalue_F2.csv vectorstats/2_out/Fvalue_F2.csv -frac 1e-6
testing_diff_matrix tmpout/Zstat_F1.csv vectorstats/2_out/Zstat_F1.csv -frac 1e-6
testing_diff_matrix tmpout/Zstat_F2.csv vectorstats/2_out/Zstat_F2.csv -frac 1e-6
testing_diff_matrix tmpout/Zstat_t1.csv vectorstats/2_out/Zstat_t1.csv -frac 1e-6
testing_diff_matrix tmpout/Zstat_t2.csv vectorstats/2_out/Zstat_t2.csv -frac 1e-6
testing_diff_matrix tmpout/Zstat_t3.csv vectorstats/2_out/Zstat_t3.csv -frac 1e-5
testing_diff_matrix tmpout/Zstat_t4.csv vectorstats/2_out/Zstat_t4.csv -frac 1e-6
testing_diff_matrix tmpout/abs_effect_t1.csv vectorstats/2_out/abs_effect_t1.csv -frac 1e-6
testing_diff_matrix tmpout/abs_effect_t2.csv vectorstats/2_out/abs_effect_t2.csv -frac 1e-6
testing_diff_matrix tmpout/abs_effect_t3.csv vectorstats/2_out/abs_effect_t3.csv -frac 1e-5
testing_diff_matrix tmpout/abs_effect_t4.csv vectorstats/2_out/abs_effect_t4.csv -frac 1e-6
testing_diff_matrix tmpout/betas.csv vectorstats/2_out/betas.csv -frac 1e-5
testing_diff_matrix tmpout/cond.csv vectorstats/2_out/cond.csv -frac 1e-6
testing_diff_matrix tmpout/std_dev.csv vectorstats/2_out/std_dev.csv -frac 1e-6
testing_diff_matrix tmpout/std_effect_t1.csv vectorstats/2_out/std_effect_t1.csv -frac 1e-6
testing_diff_matrix tmpout/std_effect_t2.csv vectorstats/2_out/std_effect_t2.csv -frac 1e-6
testing_diff_matrix tmpout/std_effect_t3.csv vectorstats/2_out/std_effect_t3.csv -frac 1e-5
testing_diff_matrix tmpout/std_effect_t4.csv vectorstats/2_out/std_effect_t4.csv -frac 1e-6
testing_diff_matrix tmpout/tvalue_t1.csv vectorstats/2_out/tvalue_t1.csv -frac 1e-6
testing_diff_matrix tmpout/tvalue_t2.csv vectorstats/2_out/tvalue_t2.csv -frac 1e-6
testing_diff_matrix tmpout/tvalue_t3.csv vectorstats/2_out/tvalue_t3.csv -frac 1e-5
testing_diff_matrix tmpout/tvalue_t4.csv vectorstats/2_out/tvalue_t4.csv -frac 1e-6

vectorstats/test2.py tmpout/
