#!/bin/bash
# vectorstats test 4
#
# Prior version where test data were genrated on request:
# N=16 SNR=5 vectorstats/gen4.py
# vectorstats tmpsubjects.txt tmpdesign.csv tmpcontrast.csv tmpout/ -errors ise
# vectorstats/test4.py
rm -rf tmpout/
vectorstats vectorstats/4_in/subjects.txt vectorstats/4_in/design.csv tmpout/ \
    -ttests vectorstats/4_in/contrast.csv \
    -errors ise

testing_diff_matrix tmpout/Zstat.csv vectorstats/4_out/Zstat.csv -frac 1e-6
testing_diff_matrix tmpout/abs_effect.csv vectorstats/4_out/abs_effect.csv -frac 1e-6
testing_diff_matrix tmpout/betas.csv vectorstats/4_out/betas.csv -frac 1e-6
testing_diff_matrix tmpout/cond.csv vectorstats/4_out/cond.csv -frac 1e-6
testing_diff_matrix tmpout/std_dev.csv vectorstats/4_out/std_dev.csv -frac 1e-6
testing_diff_matrix tmpout/std_effect.csv vectorstats/4_out/std_effect.csv -frac 1e-6
testing_diff_matrix tmpout/tvalue.csv vectorstats/4_out/tvalue.csv -frac 1e-6

vectorstats/test4.py tmpout/
