#!/bin/bash
# vectorstats test 4
#
# Prior version where test data were genrated on request:
# N=16 SNR=5 vectorstats/gen4.py
# vectorstats tmpsubjects.txt tmpdesign.csv tmpcontrast.csv tmpout/ -errors ise
# vectorstats/test4.py
rm -rf tmpout/
vectorstats vectorstats/4/subjects.txt vectorstats/4/design.csv tmpout/ \
    -ttests vectorstats/4/contrast.csv \
    -errors ise

testing_diff_matrix tmpout/Zstat.csv vectorstats/4/outZstat.csv -frac 1e-6
testing_diff_matrix tmpout/abs_effect.csv vectorstats/4/outabs_effect.csv -frac 1e-6
testing_diff_matrix tmpout/betas.csv vectorstats/4/outbetas.csv -frac 1e-6
testing_diff_matrix tmpout/cond.csv vectorstats/4/outcond.csv -frac 1e-6
testing_diff_matrix tmpout/std_dev.csv vectorstats/4/outstd_dev.csv -frac 1e-6
testing_diff_matrix tmpout/std_effect.csv vectorstats/4/outstd_effect.csv -frac 1e-6
testing_diff_matrix tmpout/tvalue.csv vectorstats/4/outtvalue.csv -frac 1e-6

vectorstats/test4.py
