#!/bin/bash
# Verify the "to_symmetric" operation, when input are lower triangular
# Input:
# [[1, 0, 0],
#  [2, 3, 0],
#  [4, 5, 6]]
# Output:
# [[1, 2, 4],
#  [2, 3, 5],
#  [4, 5, 6]]
printf $"1 0 0\n2 3 0\n4 5 6\n" > tmp.txt
connectomeedit -force tmp.txt to_symmetric tmp1.txt
printf $"1 2 4\n2 3 5\n4 5 6\n" > tmp2.txt
testing_diff_matrix tmp1.txt tmp2.txt
