#!/bin/bash
# Verify "transpose" operation
# Input:
# [[1, 2, 3],
#  [4, 5, 6],
#  [7, 8, 9]]
# Output:
# [[1, 4, 7],
#  [2, 5, 8],
#  [3, 6, 9]]
printf $"1 2 3\n4 5 6\n7 8 9\n" > tmp.txt
connectomeedit -force tmp.txt transpose tmp1.txt
printf $"1 4 7\n2 5 8\n3 6 9\n" > tmp2.txt
testing_diff_matrix tmp1.txt tmp2.txt
