#!/bin/bash
# Verify "upper_triangular" operation, when input data are symmetric
# Input:
# [[1, 2, 3],
#  [2, 4, 5],
#  [3, 5, 6]]
# Output:
# [[1, 2, 3],
#  [0, 4, 5],
#  [0, 0, 6]]
printf $"1 2 3\n2 4 5\n3 5 6\n" > tmp.txt
connectomeedit -force tmp.txt upper_triangular tmp1.txt
printf $"1 2 3\n0 4 5\n0 0 6\n" > tmp2.txt
testing_diff_matrix tmp1.txt tmp2.txt
