#!/bin/bash
# Verify "upper_triangular" operation, when input data are lower triangular
# Input:
# [[1, 0, 0],
#  [2, 3, 0],
#  [4, 5, 6]]
# Output:
# [[1, 2, 4],
#  [0, 3, 5],
#  [0, 0, 6]]
printf $"1 0 0\n2 3 0\n4 5 6\n" > tmp.txt
connectomeedit -force tmp.txt upper_triangular tmp1.txt
printf $"1 2 4\n0 3 5\n0 0 6\n" > tmp2.txt
testing_diff_matrix tmp1.txt tmp2.txt
