#!/bin/bash
# Verify that "upper_triangular" operation fails when input data are asymmetric
# Input:
# [[1, 2, 3],
#  [4, 5, 6],
#  [7, 8, 9]]
printf $"1 2 3\n4 5 6\n7 8 9\n" > tmp.txt
connectomeedit -force tmp.txt upper_triangular tmp1.txt || true && false
