#!/bin/bash
# Verify "zero_diagonal" operation
# Input:
# [[1, 2, 3],
#  [4, 5, 6],
#  [7, 8, 9]]
# Output:
# [[0, 2, 3]
#  [4, 0, 6],
#  [7, 8, 0]]
printf $"1 2 3\n4 5 6\n7 8 9\n" > tmp.txt
connectomeedit -force tmp.txt zero_diagonal tmp1.txt
printf $"0 2 3\n4 0 6\n7 8 0\n" > tmp2.txt
testing_diff_matrix tmp1.txt tmp2.txt
