#!/bin/bash
# Test amp2response with the -lmax option:
#   estimate a response function restricted to lmax=6.
# The test verifies that the command runs successfully and produces
#   an output with the correct number of ZSH coefficients for lmax=6.
amp2response dwi.mif sh2response/sf.mif sh2response/ev.mif tmp.txt \
    -lmax 6 \
    -force
