#!/bin/bash
# Test successful execution for a single subset
#   where the -firstisfirst option is specified
# Cannot compare directly to a pre-generated output due to stochasticity of command

dirmerge 1 \
0 dirmerge/bzero_8.txt \
300 dirmerge/12.txt \
1000 dirmerge/24.txt \
3000 dirmerge/60.txt \
tmp.txt -force -firstisfirst
