#!/bin/bash
# Ensure that an image can be written to MGH format,
#   and then subsequently read and interpreted as being identical to the original
mrconvert mrconvert/in.mif tmp.mgh -force
testing_diff_image tmp.mgh mrconvert/in.mif
