#!/bin/bash
# Verify execution of "dwi2mask b02template", when:
# - Software selection is "fsl",
#   which invokes FSL commands flirt and fnirt
# - The configuration file to be provided to FSL command fnirt
#   is specified with an absolute path within the MRtrix config file;
#   since the test cannot modify the user's config file,
#   this is simulated by using the standard command-line option "-config"
dwi2mask b02template BIDS/sub-01/dwi/sub-01_dwi.nii.gz tmp.mif -force \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval \
-software fsl \
-template dwi2mask/template_image.mif.gz dwi2mask/template_mask.mif.gz \
-config Dwi2maskTemplateFSLFnirtConfig $(pwd)/dwi2mask/fnirt_config.cnf
