#!/bin/bash
# Verify operation of "dwi2mask b02template" command, when:
# - Software choice is "antsquick",
#   which invokes ANTs command "antsRegistrationSyNQuick.sh"
# - Standard command-line option "-config" is used
#   to pass command-line options to that ANTs command
#   as though the user had specified it in their config file
dwi2mask b02template BIDS/sub-01/dwi/sub-01_dwi.nii.gz tmp.mif -force \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval \
-software antsquick \
-template dwi2mask/template_image.mif.gz dwi2mask/template_mask.mif.gz \
-config Dwi2maskTemplateANTsQuickOptions "-t r"
