#!/bin/bash
# Verify operation of the "dwi2mask b02template" command
#   when image paths include whitespace characters
# Ensure that the output image appears at the expected location
rm -f "tmp out.mif"

ln -s BIDS/sub-01/dwi/sub-01_dwi.nii.gz "tmp in.nii.gz"
ln -s BIDS/sub-01/dwi/sub-01_dwi.bvec "tmp in.bvec"
ln -s BIDS/sub-01/dwi/sub-01_dwi.bval "tmp in.bval"

ln -s dwi2mask/template_image.mif.gz "tmp template.mif.gz"
ln -s dwi2mask/template_mask.mif.hz "tmp mask.mif.gz"

dwi2mask b02template "tmp in.mif" "tmp out.mif" -force \
-fslgrad "tmp in.bvec" "tmp in.bval" \
-software antsquick \
-template "tmp template.mif.gz" "tmp mask.mif.gz"

ls | grep "^tmp out\.mif$"
