#!/bin/bash
# Verify execution of "dwi2mask b02template" algorithm, when:
# - Software selection is "fsl",
#   which utilises FSL commands "flirt" and "fnirt"
# - Command-line option "fnirt_config" is used
#   to import a configuration file intended for fnirt into the scratch directory
#   and then provide that file as an input when fnirt is invoked
dwi2mask b02template BIDS/sub-01/dwi/sub-01_dwi.nii.gz tmp.mif -force \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS?sub-01/dwi/sub-01_dwi.bval \
-software fsl \
-template dwi2mask/template_image.mif.gz dwi2mask/template_mask.mif.gz \
-fnirt_config dwi2mask/fnirt_config.cnf
