#!/bin/bash
# Ensure successful execution of "dwi2mask fslbet" algorithm
#   when making use of image pipes
mrconvert BIDS/sub-01/dwi/sub-01_dwi.nii.gz - \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval | \
dwi2mask fslbet - - | \
mrconvert - tmp.mif -force
