#!/bin/bash
# Verify successful execution of "dwi2mask fslbet" algorithm,
#   which invokes FSL command "bet",
#   when command-line option "-rescale" is utilised,
#   which modifies voxel spacing to make images of species of different spatial scale
#   to approximate that of human adult in vivo imaging
dwi2mask fslbet BIDS/sub-01/dwi/sub-01_dwi.nii.gz tmp.mif -force \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval \
-rescale
