#!/bin/bash
# Verify successful execution of "dwi2mask hdbet" algorithm
#   when using image piping
mrconvert BIDS/sub-01/dwi/sub-01_dwi.nii.gz - \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval | \
dwi2mask hdbet - - | \
mrconvert - tmp.mif -force
