#!/bin/bash
# Verify successful execution of "dwi2mask hdbet" algorithm
#   under default operation
dwi2mask hdbet BIDS/sub-01/dwi/sub-01_dwi.nii.gz tmp.mif -force \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval
