#!/bin/bash
# Ensure correct operation of the "dwi2mask legacy" command
#   when both input and output images are pipes
mrconvert BIDS/sub-01/dwi/sub-01_dwi.nii.gz - \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval | \
dwi2mask legacy - - | \
testing_diff_image - dwi2mask/legacy.mif.gz
