#!/bin/bash
# Verify "dwi2mask mean" algorithm
#   when used in conjunction with image pipes
mrconvert BIDS/sub-01/dwi/sub-01_dwi.nii.gz - \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval | \
dwi2mask mean - - | \
testing_diff_image - dwi2mask/mean.mif.gz
