#!/bin/bash
# Verify "dwi2mask mean" algorithm
#   under default operation
dwi2mask mean BIDS/sub-01/dwi/sub-01_dwi.nii.gz - \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval | \
testing_diff_image - dwi2mask/mean.mif.gz
