#!/bin/bash
# Verify "dwi2mask mtnorm" algorithm,
#   when all behaviour is default
dwi2mask mtnorm BIDS/sub-01/dwi/sub-01_dwi.nii.gz tmpmask.mif -force \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval \
-tissuesum tmptissuesum.mif

testing_diff_image tmpmask.mif dwi2mask/mtnorm_default_mask.mif.gz
testing_diff_image tmptissuesum.mif dwi2mask/mtnorm_default_tissuesum.mif.gz -abs 1e-5
