#!/bin/bash
# Verify operation of "dwi2mask mtnorm" algorithm,
#   when manually overriding the maximal spherical harmonic degree per tissue
dwi2mask mtnorm BIDS/sub-01/dwi/sub-01_dwi.nii.gz tmpmask.mif -force \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval \
-lmax 6,0,0 \
-tissuesum tmptissuesum.mif

testing_diff_image tmpmask.mif dwi2mask/mtnorm_lmax600_mask.mif.gz
testing_diff_image tmptissuesum.mif dwi2mask/mtnorm_lmax600_tissuesum.mif.gz -abs 1e-5
