#!/bin/bash
# Ensure correct operation of the "dwi2mask mtnorm" command
#   when image pipes are used to specify inputs / outputs

# Input and output images both piped
mrconvert BIDS/sub-01/dwi/sub-01_dwi.nii.gz - \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval | \
dwi2mask mtnorm - - | \
testing_diff_image - dwi2mask/mtnorm_default_mask.mif


# Output tissue sum image is piped
dwi2mask mtnorm BIDS/sub-01/dwi/sub-01_dwi.nii.gz tmp.mif -force \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval \
-tissuesum - | \
testing_diff_image - dwi2mask/mtnorm_default_tissuesum.mif.gz -abs 1e-5
