#!/bin/bash
# Ensure correct operation of the "dwi2mask synthstrip" command
#   where image paths include whitespace characters
# Check that expected output images appear
rm -f "tmp out.mif" "tmp stripped.mif"

ln -s BIDS/sub-01/dwi/sub-01_dwi.nii.gz "tmp in.nii.gz"
ln -s BIDS/sub-01/dwi/sub-01_dwi.bvec "tmp in.bvec"
ln -s BIDS/sub-01/dwi/sub-01_dwi.bval "tmp in.bval"

dwi2mask synthstrip "tmp in.mif" "tmp out.mif" -force \
-fslgrad "tmp in.bvec" "tmp in.bval" \
-stripped "tmp stripped.mif"

ls | grep "^tmp out\.mif"
ls | grep "^tmp stripped\.mif"
