#!/bin/bash
# Verify result of "dwi2mask trace" algorithm
#   when executed under default behaviour
dwi2mask trace BIDS/sub-01/dwi/sub-01_dwi.nii.gz tmp.mif -force \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval

testing_diff_image tmp.mif dwi2mask/trace_default.mif.gz
