#!/bin/bash
# Verify result of "dwi2mask trace" algorithm,
#   when the iterative optimisation algorithm is engaged
dwi2mask trace BIDS/sub-01/dwi/sub-01_dwi.nii.gz - \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval \
-iterative | \
testing_diff_image - dwi2mask/trace_iterative.mif.gz
