#!/bin/bash
# Verify result of "dwi2mask trace" algorithm
#   when utilising images that have whitespaces in their paths
rm -rf "tmp scratch"

ln -s BIDS/sub-01/dwi/sub-01_dwi.nii.gz "tmp in.nii.gz"
ln -s BIDS/sub-01/dwi/sub-01_dwi.bvec "tmp in.bvec"
ln -s BIDS/sub-01/dwi/sub-01_dwi.bval "tmp in.bval"

mkdir "tmp scratch"

dwi2mask trace "tmp in.nii.gz" "tmp out.mif" -force \
-fslgrad "tmp in.bvec" "tmp in.bval" \
-scratch "tmp scratch"

testing_diff_image "tmp out.mif" dwi2mask/trace_default.mif.gz
