#!/usr/bin/python
import sys
import string


if len(sys.argv) < 3 :
  print "average_response response1.txt response2.txt response3.txt average_response.txt"
  exit(1)

commandString = string.join(sys.argv[1:])

all_response = []
for i in range(1,len(sys.argv)-1):
  with open(sys.argv[i], 'r') as f:
    all_response.append([float(x) for x in f.readline().split()])

num_SH_coeff = len(all_response[0])
num_subjects = len(all_response)
average_response = [0] * num_SH_coeff

for r in all_response:
  for i in range(0, num_SH_coeff):
    average_response[i] = average_response[i] + r[i] / num_subjects

f = open(sys.argv[len(sys.argv)-1], 'w')
line_out = ''
for i in average_response:
  line_out = line_out + "{0:.5f}".format(i) + ' '
f.write("%s\n" % line_out)