#!/usr/bin/env python

# Script that performs B1 field inhomogeneity correction for a DWI volume series
# Bias field is estimated using the mean b=0 image, and subsequently used to correct all volumes


import os, sys
import lib.app

from lib.binaryInPath  import binaryInPath
from lib.errorMessage  import errorMessage
from lib.getFSLSuffix  import getFSLSuffix
from lib.getHeaderInfo import getHeaderInfo
from lib.isWindows     import isWindows
from lib.runCommand    import runCommand

lib.app.author = 'Robert E. Smith (robert.smith@florey.edu.au)'
lib.app.initCitations([ 'fast', 'FSL' ])
lib.app.initParser('Perform B1 field inhomogeneity correction for a DWI volume series')
lib.app.parser.add_argument('input',  help='The input image series to be corrected')
lib.app.parser.add_argument('output', help='The output corrected image series')
lib.app.initialise()

if isWindows():
  errorMessage('Script cannot run on Windows due to FSL dependency')

fsl_path = os.environ.get('FSLDIR', '')
if not fsl_path:
  errorMessage('Environment variable FSLDIR is not set; please run appropriate FSL configuration script')

fast_cmd = 'fast'
if not binaryInPath(fast_cmd):
  fast_cmd = 'fsl5.0-fast'
  if not binaryInPath(fast_cmd):
    errorMessage('Could not find FSL program fast; please verify FSL install')
    
fsl_suffix = getFSLSuffix()
if fast_cmd == 'fast':
  fast_suffix = fsl_suffix
else:
  fast_suffix = '.nii.gz'

runCommand('mrconvert ' + lib.app.args.input + ' ' + os.path.join(lib.app.tempDir, 'in.mif'))

lib.app.gotoTempDir()

# Make sure it's actually a DWI that's been passed
dims = getHeaderInfo('in.mif', 'dim').split()
if len(dims) != 4:
  errorMessage('Input image must be a 4D image')
DW_scheme = getHeaderInfo('in.mif', 'dwgrad').split('\n')
if len(DW_scheme) != int(dims[3]):
  errorMessage('Input image does not contain valid DW gradient scheme')

# Generate a brain mask
runCommand('dwi2mask in.mif mask.mif')

# Give FSL a compatible image
runCommand('dwiextract in.mif - -bzero | mrcalc - mask.mif -mult bzeros.mif')
bzero_dim = getHeaderInfo('bzeros.mif', 'dim')
if len(bzero_dim) == 4:
  runCommand('mrmath bzeros.mif mean - -axis 3 | mrconvert - mean_bzero.nii -stride +1,+2,+3')
else:
  runCommand('mrconvert bzeros.mif mean_bzero.nii -stride +1,+2,+3')

runCommand(fast_cmd + ' -t 2 -o fast -n 3 -b mean_bzero.nii')

runCommand('mrcalc in.mif fast_bias' + fast_suffix + ' -div result.mif')
runCommand('mrconvert result.mif ' + os.path.join(lib.app.workingDir, lib.app.args.output) + lib.app.mrtrixForce)

lib.app.complete()

