#!/usr/bin/python2

# Script for 'repairing' a FreeSurfer parcellation image
# FreeSurfer's sub-cortical structure segmentation has been observed to be highly variable
#   under scan-rescan conditions. This introduces unwanted variability into the connectome,
#   as the parcellations don't overlap with the sub-cortical segmentations provided by
#   FIRST for the sake of Anatomically-Constrained Tractography. This script determines the
#   node indices that correspond to these structures, and replaces them with estimates
#   derived from FIRST.
# This script can be used in one of two ways. Firstly, it can directly change the nodes in
#   one of FreeSurfer's segmentation outputs, by providing the file FreeSurferColorLUT.tx
#   as the lookup table file. If such a segmentation has already been processed using
#   mrprep4connectome, then provide the connectome config file used. These are necessary to
#   determine which integer values correspond to the sub-cortical grey matter structres
#   that are being re-defined.


import os, shutil, sys

from lib.binaryInPath import binaryInPath
from lib.delTempDir   import delTempDir
from lib.errorMessage import errorMessage
from lib.getFSLSuffix import getFSLSuffix
from lib.loadOptions  import loadOptions
from lib.makeTempDir  import makeTempDir
from lib.printMessage import printMessage
from lib.runCommand   import runCommand

num_args = 4

if len(sys.argv) < num_args+1:
  errorMessage('Usage: ' + os.path.basename(sys.argv[0]) + ' <input parcellation image> <input T1 image> <lookup table file> <output parcellation image>')

fsl_path = os.environ.get('FSLDIR', '')
if not fsl_path:
  errorMessage('Environment variable FSLDIR is not set; please run appropriate FSL configuration script')

first_cmd = 'run_first_all'
if not binaryInPath(first_cmd):
  first_cmd = "fsl5.0-run_first_all"
  if not binaryInPath(first_cmd):
    errorMessage('Could not find FSL program run_first_all; please verify FSL install')

first_atlas_path = os.path.join(fsl_path, 'data', 'first', 'models_336_bin')

if not os.path.isdir(first_atlas_path):
  errorMessage('Atlases required for FSL\'s FIRST program not installed;\nPlease install fsl-first-data using your relevant package manager')

(quiet, verbose) = loadOptions(num_args)

fsl_suffix = getFSLSuffix()

working_dir = os.getcwd()
temp_dir = makeTempDir(verbose)
  
# Want a mapping between FreeSurfer node names and FIRST structure names
# Just deal with the 5 that are used in ACT; FreeSurfer's hippocampus / amygdala segmentations look good enough.
structure_map = { 'L_Accu':'Left-Accumbens-area',  'R_Accu':'Right-Accumbens-area', 
                  'L_Caud':'Left-Caudate',         'R_Caud':'Right-Caudate',
                  'L_Pall':'Left-Pallidum',        'R_Pall':'Right-Pallidum',
                  'L_Puta':'Left-Putamen',         'R_Puta':'Right-Putamen',
                  'L_Thal':'Left-Thalamus-Proper', 'R_Thal':'Right-Thalamus-Proper' }
                  
# Import the config file
# Invert the mapping - go from the structure name to the index
config = {}
with open(sys.argv[3]) as f:
  for line in f:
    line = line.rstrip()
    if line and line[0]!='#':
       line = line.split()
       config[line[1]] = line[0] # This can remain as a string

# Get the parcellation and T1 images into the temporary directory, with conversion of the T1 into the correct format for FSL
runCommand('mrconvert ' + sys.argv[1] + ' ' + os.path.join(temp_dir, 'parc.mif') + quiet, verbose)
runCommand('mrconvert ' + sys.argv[2] + ' ' + os.path.join(temp_dir, 'T1.nii')   + ' -stride +1,+2,+3' + quiet, verbose)

if verbose:
  printMessage('Changing to temporary directory (' + temp_dir + ')')
os.chdir(temp_dir)

runCommand(first_cmd + ' -s ' + ','.join(structure_map.keys()) + ' -i T1.nii -o first', verbose)

# Convert FIRST meshes to node masks
# In this use case, don't want the PVE images; want to threshold at 0.5
mask_list = [ ]
for struct in structure_map.keys():
  image_path = struct + '_mask.nii'
  mask_list.append (image_path)
  runCommand('mesh2pve first-' + struct + '_first.vtk parc.mif - -first T1.nii' + quiet + ' | mrthreshold - ' + image_path + ' -abs 0.5' + quiet, verbose)
  # Replace the node location in the parcellation image with the new mask image
  node_index = config[structure_map[struct]]
  runCommand('mrmath parc.mif ' + node_index + ' -neq parc.mif -mult parc_old_removed.mif' + quiet, verbose)
  # Can't add images here - may have overlap with existing nodes
  # Instead, set to the desired node index value if the mask is true, or use the existing value in the image otherwise
  runCommand('mrmath ' + image_path + ' ' + node_index + ' parc_old_removed.mif -if parc_new_inserted.mif' + quiet, verbose)
  os.remove('parc.mif')
  os.remove('parc_old_removed.mif')
  os.rename('parc_new_inserted.mif', 'parc.mif')

# Detect any overlapping voxels between these masks
# These will be set to 0 in the final parcellated image
runCommand('mrcat ' + ' '.join(mask_list) + ' - -axis 3' + quiet + ' | mrmathaxis - sum 3 -' + quiet + ' | mrmath - 1 -gt overlap_mask.nii' + quiet, verbose)
runCommand('mrmath overlap_mask.nii 0 parc.mif -if ' + os.path.basename(sys.argv[4]) + quiet, verbose)

# Move back to original directory
if verbose:
  printMessage('Changing back to original directory (' + working_dir + ')')
os.chdir(working_dir)

# Get the final file from the temporary directory & put it in the correct location
if verbose:
  printMessage('Moving output file from temporary directory to user specified location')
shutil.move(os.path.join(temp_dir, os.path.basename(sys.argv[4])), sys.argv[4])

# Don't leave a trace
delTempDir(temp_dir, verbose)

