#!/usr/bin/python2
import os
import sys
import string
import getCommonTail
import jobLauncher

inputFiles = os.listdir(os.getcwd())
common = getCommonTail.get(inputFiles)

if len(common) == 0:
  print "no common postfix found, check for additional files in your directory"
  exit(1)

if not jobLauncher.is_int(sys.argv[1]):
  print 'the first argument must specify the number of threads to be used'
  exit(1)
threads = int(sys.argv[1])
commandString = string.join(sys.argv[2:])

jobs = []
for i in inputFiles:
  p = string.split(i,common)[0]
  job = commandString.replace('IN', i)
  job = job.replace('PRE', p)
  job = job + ' >/dev/null 2>&1'
  jobs.append(job)
jobLauncher.launchLocal(jobs, threads);