#!/usr/bin/python2
import os
import sys
import string
import getCommonTail
import jobLauncher


inputFiles = os.listdir(os.getcwd())
common = getCommonTail.get(inputFiles)

if len(common) == 0:
  print "no common postfix found, check for additional files in your directory"
  exit(1)

commandString = string.join(sys.argv[1:])

for i in inputFiles:
  p = string.split(i,common)[0]
  job = commandString.replace('IN', i)
  job = job.replace('PRE', p)
  jobLauncher.launchJobs(job)