#!/usr/bin/env python2
import os
import sys
import string

def get(inputFiles):
  first = inputFiles[0];
  cursor = 0
  found = False;
  common = ''
  for i in reversed(first):
    if found == False:
      for j in inputFiles:
        if j[len(j)-cursor-1] != first[len(first)-cursor-1]:
          found = True
          break
      if found == False:
        common = first[len(first)-cursor-1] + common
      cursor += 1
  return common

def run_command(cmd):
  if (os.system(cmd)):
    print 'Command failed: ' +  cmd
    exit(1)

inputFiles = os.listdir(os.getcwd())
common = get(inputFiles)

if len(common) == 0:
  print "no common postfix found, check for additional files in your directory"
  exit(1)

commandString = string.join(sys.argv[1:])

for i in inputFiles:
  p = string.split(i,common)[0]
  job = commandString.replace('IN', i)
  job = job.replace('PRE', p)
  run_command(job)
