#!/usr/bin/python2
import os
import sys
import string
import getCommonTail
import jobLauncher

inputFiles = os.listdir(os.getcwd())
common = getCommonTail.get(inputFiles)

if len(common) == 0:
  print "no common postfix found, check for additional files in your directory"
  exit(1)

commandString = string.join(sys.argv[1:])

jobs =''
for i in inputFiles:
  jobs = jobs + commandString.replace('IN', i).replace('PRE', string.split(i,common)[0]) + '; '
jobLauncher.launchJobs(job)