#!/usr/bin/python2
import os
import sys
import string

def run_command(cmd):
  if (os.system(cmd)):
    print 'Command failed: ' +  cmd
    exit(1)

dirs = [d for d in os.listdir(os.getcwd()) if os.path.isdir(os.path.join(os.getcwd(), d))]

if len(dirs) == 0:
  print "no directories found"
  exit(1)

commandString = string.join(sys.argv[1:])

for i in dirs:
  job = commandString.replace('DIR', i)
  run_command(job)