#!/usr/bin/python2
import os
import sys
import string
import jobLauncher

dirs = [d for d in os.listdir(os.getcwd()) if os.path.isdir(os.path.join(os.getcwd(), d))]

if len(dirs) == 0:
  print "no directories found"
  exit(1)

commandString = string.join(sys.argv[1:])

jobs = ''
for i in dirs:
  jobs = commandString.replace('DIR', i) + '; '
jobLauncher.launchJobs(jobs)
