#!/usr/bin/python2
import os
import sys
import string
import jobLauncher

dirs = [d for d in os.listdir(os.getcwd()) if os.path.isdir(os.path.join(os.getcwd(), d))]

if len(dirs) == 0:
  print "no directories found"
  exit(1)

if not jobLauncher.is_int(sys.argv[1]):
  print 'the first argument must specify the number of threads to be used'
  exit(1)
threads = int(sys.argv[1])
commandString = string.join(sys.argv[2:])

jobs = []
for i in dirs:
  job = commandString.replace('DIR', i)
  job = job + ' >/dev/null 2>&1'
  jobs.append(job)
jobLauncher.launchLocal(jobs, threads);