#!/usr/bin/env python

import math, os, sys, glob
import lib.app, lib.cmdlineParser

def abspath(*arg):
  return os.path.abspath(os.path.join(*arg))

def relpath(*arg):
  return os.path.relpath(os.path.join(*arg),lib.app.workingDir)

from lib.printMessage  import printMessage
from lib.errorMessage  import errorMessage
from lib.getHeaderInfo import getHeaderInfo
from lib.getUserPath   import getUserPath
from lib.runCommand    import runCommand

lib.app.author = 'David Raffelt (david.raffelt@florey.edu.au)'
lib.cmdlineParser.initialise('Multi-Tissue Bias field correction and Intensity Normalisation (MTBIN). This script inputs N number of tissue components '
                             '(from multi-tissue CSD), and outputs N corrected tissue components. Intensity normalisation is performed using a single global scale factor for each tissue type. '
                             'Example usage: mtbin wm.mif wm_norm.mif gm.mif gm_norm.mif csf.mif csf_norm.mif')
lib.app.parser.add_argument('input_output', nargs='*', help='list of all input and output tissue compartment files. See example usage in the description. '
                            'Note that any number of tissues can be normalised')
options = lib.app.parser.add_argument_group('Options for the mtbin script')
options.add_argument('-mask',  help='define the mask to compute the normalisation within. If not supplied this is estimated automatically')
options.add_argument('-value', default='0.282094', help='specify the value to which the summed tissue compartments will be globally normalised to (Default: sqrt(1/(4*pi) = 0.282)')
options.add_argument('-iter', default='4', help='bias field correction and intensity normalisation is performed iteratively. Specify the number of iterations (Default: 4)')
lib.app.parser.add_argument('-bias', help='Output estimated bias field')


lib.app.initialise()

masking = ''
if lib.app.args.mask:
  masking = ' -mask ' + relpath(lib.app.args.mask_dir) + ' '

max_iterations = int(lib.app.args.iter)

if (len(lib.app.args.input_output) % 2):
  errorMessage ("The number of input arguments must be even. There must be an output file provided for every input tissue image")

input_files = []
output_files = []
for i in range(0, len(lib.app.args.input_output)):
  if i % 2:
    lib.app.checkOutputFile(lib.app.args.input_output[i])
    output_files.append(lib.app.args.input_output[i])
  else:
    input_files.append(os.path.join(lib.app.workingDir, lib.app.args.input_output[i]))

lib.app.makeTempDir()
lib.app.gotoTempDir()

norm_files = ['norm_' + os.path.basename(s) for s in input_files]
bias_corrected_files = ['bias_' + os.path.basename(s) for s in input_files]

for iteration in range(1, max_iterations + 1):
  printMessage('iteration: ' + str(iteration))

  # normalise to 1 while estimating the bias field for output
  if iteration == 1:
    runCommand('mtnormalise -force -value 1.0 ' + masking + ' '.join([x for t in zip(input_files, norm_files) for x in t]))
  else:
    runCommand('mtnormalise -force -value 1.0 ' + masking + ' '.join([x for t in zip(bias_corrected_files, norm_files) for x in t]))

  files_to_sum = []
  for f in norm_files:
    sizes = getHeaderInfo(f, 'size').split()
    if len(sizes) > 3 and int(sizes[3]) > 1:
      dc_file_name = 'dc_' + f
      runCommand('mrconvert -force -coord 3 0 ' + f + ' ' + dc_file_name)
      files_to_sum.append(dc_file_name)
    else:
      files_to_sum.append(f)
  runCommand('mrmath ' + ' '.join(files_to_sum) + ' sum summed.mif -force')
  runCommand('mrmodelfield summed.mif field' + str(iteration) + '.mif -force' + masking)

  for a, b in zip(norm_files, bias_corrected_files):
    runCommand('mrcalc -force ' + a + ' field' + str(iteration) + '.mif -divide ' + b)
  files_to_normalise = bias_corrected_files

# Final normalisation to value desired by user
runCommand('mtnormalise -force -value ' + lib.app.args.value + ' ' + masking + ' '.join([x for t in zip(bias_corrected_files, norm_files) for x in t]))

for a, b in zip(norm_files, output_files):
  runCommand('mrconvert ' + a + ' ' + getUserPath(b, True) + lib.app.mrtrixForce)

# combine all fields from each iteration for output
if lib.app.args.bias:
  runCommand('mrmath ' + ' '.join(glob.glob('field*.mif')) + ' product total_field.mif')
  runCommand('mrconvert total_field.mif ' + getUserPath(lib.app.args.bias, True) + lib.app.mrtrixForce)

lib.app.complete()
