#!/usr/bin/python2

# Script for performing EPI distortion correction using FSL 5.0 tools eddy / topup / applytopup

# This script is only for the specific case where a single pair of reversed-phase-encode images have been acquired for estimating the inhomogeneity field (phase encode A>>P then P>>A), which is to be used subsequently to correct a volume series (DWI / fMRI) that has been acquired using A>>P phase-encode direction. If your acquisition is different or more complex, you will need to modify this script accordingly or make your own.

# Unlike the previous version of this script, this now uses FSL's eddy tool to perform motion & eddy current correction as well as susceptibility distortion correction for DWI. Therefore the input images to this script should be the images as they are received from the scanner i.e. it is no longer necessary to perform DWI motion correction before running this script. However, if it is an fMRI time series that is being processed, eddy is not applicable, so motion correction will need to be applied prior to this script, and this script is only responsible for the susceptibility distortion correction. (Perhaps down the track FMRIB will modify mcflirt to use the field output from topup...?)

# Order of input arguments is:
# * Anterior-posterior image from reverse phase-encode pair
# * Posterior-anterior image from reverse phase-encode pair
# * Image series to be corrected
# * Name of output corrected image series


import os, shutil, sys

from lib.binaryInPath  import binaryInPath
from lib.delTempDir    import delTempDir
from lib.errorMessage  import errorMessage
from lib.getFSLSuffix  import getFSLSuffix
from lib.getHeaderInfo import getHeaderInfo
from lib.loadOptions   import loadOptions
from lib.makeTempDir   import makeTempDir
from lib.printMessage  import printMessage
from lib.runCommand    import runCommand
from lib.warnMessage   import warnMessage


num_args = 4

if len(sys.argv) < num_args+1:
  errorMessage('Usage: ' + os.path.basename(sys.argv[0]) + ' <AP image> <PA image> <Input image series> <Output image series>')

fsl_path = os.environ.get('FSLDIR', '')
if not fsl_path:
  errorMessage('Environment variable FSLDIR is not set; please run appropriate FSL configuration script')

topup_config_path = os.path.join(fsl_path, 'etc', 'flirtsch', 'b02b0.cnf')
if not os.path.isfile(topup_config_path):
  errorMessage('Could not find necessary default config file for FSL\'s topup program\n(expected location: ' + topup_config_path + ')')

topup_cmd = 'topup'
if not binaryInPath(topup_cmd):
  topup_cmd = 'fsl5.0-topup'
  if not binaryInPath(topup_cmd):
    errorMessage('Could not find FSL program topup; please verify FSL install')

applytopup_cmd = 'applytopup'
if not binaryInPath(applytopup_cmd):
  applytopup_cmd = 'fsl5.0-applytopup'
  if not binaryInPath(applytopup_cmd):
    errorMessage('Could not find FSL program applytopup; please verify FSL install')
    
eddy_cmd = 'eddy'
if not binaryInPath(eddy_cmd):
  eddy_cmd = 'fsl5.0-eddy'
  if not binaryInPath(eddy_cmd):
    errorMessage('Could not find FSL program eddy; please verify FSL install')

(quiet, verbose) = loadOptions(num_args)

fsl_suffix = getFSLSuffix()

working_dir = os.getcwd()
temp_dir = makeTempDir(verbose)

# Convert all input images into MRtrix format and store in temprary directory first;
#   that way getHeaderInfo() can be run multiple times without having to repeatedly parse e.g. DICOM data
runCommand('mrconvert ' + sys.argv[1] + ' ' + os.path.join(temp_dir, 'AP.mif')     + quiet, verbose)
runCommand('mrconvert ' + sys.argv[2] + ' ' + os.path.join(temp_dir, 'PA.mif')     + quiet, verbose)
runCommand('mrconvert ' + sys.argv[3] + ' ' + os.path.join(temp_dir, 'series.mif') + quiet, verbose)

# Move into the temporary directory
if verbose:
  printMessage('Changing to temporary directory (' + temp_dir + ')')
os.chdir(temp_dir)

# Verify that input images are valid
AP_dim     = getHeaderInfo ('AP.mif',     'dimensions', verbose).split()
PA_dim     = getHeaderInfo ('PA.mif',     'dimensions', verbose).split()
series_dim = getHeaderInfo ('series.mif', 'dimensions', verbose).split()

if len(AP_dim) != 3:
  if not (len(AP_dim) == 4 and AP_dim[3] == 1):
    errorMessage ('First image of reversed phase-encode pair must be a 3D image')
if len(PA_dim) != 3:
  if not (len(PA_dim) == 4 and PA_dim[3] == 1):
    errorMessage ('Second image of reversed phase-encode pair must be a 3D image')
if AP_dim != PA_dim:
  errorMessage ('Dimensions of reversed phase-encode image pair do not match')
if series_dim[:3] != AP_dim:
  errorMessage ('Spatial dimensions of volume series does not match reversed-PE pair')
if len(series_dim) != 4:
  errorMessage ('Third input image should be a 4D volume series')
  
# Get the axis strides from the input series, so the output image can be modified to match
stride = getHeaderInfo ('series.mif', 'stride', verbose)
stride_option = ' -stride ' + stride.replace(' ', ',')

# Test to see if there is any diffusion gradient encoding in the input series
grad = getHeaderInfo ('series.mif', 'dwgrad', verbose)

# Convert the input files as necessary for FSL tools
runCommand('mrcat AP.mif PA.mif - -axis 3' + quiet + ' | mrconvert - pair.nii -stride +1,+2,+3,+4' + quiet, verbose)
runCommand('mrconvert series.mif series_before.nii -stride +1,+2,+3,+4' + quiet, verbose)

# If no axes need to be cropped, use the original 4D volume with the image pair
# Otherwise, need to call mrcrop with the appropriate options, and pass the modified images to topup
topup_imain = 'pair.nii'
series_imain = 'series_before.nii'

# For any non-even dimensions, crop the first voxel along that dimension
crop_option = ''        
for axis, axis_dim in enumerate(AP_dim):
  if int(axis_dim)%2:
    crop_option += ' -axis ' + str(axis) + ' 1 ' + str(int(axis_dim)-1) 

if crop_option:
  warnMessage('Input images contain at least one non-even dimension; cropping images for topup / eddy compatibility') 
  runCommand('mrcrop pair.nii pair_crop.nii' + crop_option + quiet, verbose)
  runCommand('mrcrop series_before.nii series_crop.nii' + crop_option + quiet, verbose)
  topup_imain = 'pair_crop.nii'
  series_imain = 'series_crop.nii'

# Construct a configuration file
if verbose:
  printMessage('Creating phase-encoding configuration file')
config_file = open('config.txt', 'w')
config_file.write('0  1 0 0.1\n0 -1 0 0.1\n')
config_file.close()

# Perform the field estimation
runCommand(topup_cmd + ' --imain=' + topup_imain + ' --datain=config.txt --out=field --config=' + topup_config_path, verbose)

# Apply the warp field to the image series
# Note: applytopup appears to ignore FSLOUTPUTTYPE field, and just outputs a .nii.gz
runCommand(applytopup_cmd + ' --imain=' + series_imain + ' --datain=config.txt --inindex=1 --topup=field --out=series_topup.' + fsl_suffix + ' --method=jac', verbose)

# Need to split depending on whether DW information is available
result_path = 'result' + os.path.splitext(sys.argv[4])[1]
if not grad:

  if verbose:
    printMessage('No diffusion gradient encoding found in input file; using output from applytopup')
    
  runCommand('mrconvert series_topup.' + fsl_suffix + ' ' + result_path + stride_option + quiet, verbose) 
  
else:

  if verbose:
    printMessage('Detected diffusion gradient encoding in input file; running eddy')
    
  # Create the diffusion gradient table in FSL format
  runCommand('mrinfo series.mif -export_grad_fsl bvecs' + quiet, verbose)
    
  # Use the initial corrected image series from applytopup to derive a processing mask for eddy
  runCommand('mrconvert series_topup.' + fsl_suffix + ' -grad bvecs  -' + quiet + ' | dwi2mask - -' + quiet + ' | maskfilter - dilate -' + quiet + ' | mrconvert - mask.nii -datatype float32' + quiet, verbose)
  
  # Generate configuration file for eddy - index referring to PE and bandwidth for each volume
  # In this particular use case, we assume that every volume in the series has the same imaging parameters as the first of the reversed-PE pair
  # Therefore, every volume has an index of 1
  
  # Need to find the number of input volumes
  # For this, import bvals and count the number of entries
  bvals_input = open ('bvals', 'r')
  bvals = bvals_input.read()
  bvals = bvals.strip().split()
  num_volumes = len(bvals)
  
  indices = ''
  for volume in range(0, num_volumes):
    indices = indices + '1 '
  with open('indices.txt', 'w') as index_file:
    index_file.write(indices);
  
  # Run eddy
  fsl_verbose = ''
  if verbose:
    fsl_verbose = ' --verbose'
  runCommand('eddy --imain=' + series_imain + ' --mask=mask.nii --index=indices.txt --acqp=config.txt --bvecs=bvecs --bvals=bvals --topup=field --out=series_after' + fsl_verbose, verbose)
  
  # Convert the resulting volume to the output image, and re-insert the diffusion encoding
  # Note that currently the script uses the diffusion encoding from the original DWI volumes, i.e. no reorientation of diffusion
  #   gradient vectors is performed. It should be possible to get the motion parameters from the eddy 
  # text file output and modify them manually, or FMRIB may update eddy itself.
  runCommand('mrconvert series_after.' + fsl_suffix + ' ' + result_path + stride_option + ' -grad bvecs' + quiet, verbose) 
  

# Move back to original directory
if verbose:
  printMessage('Changing back to original directory (' + working_dir + ')')
os.chdir(working_dir)

# Get the final file from the temporary directory & put it in the correct location
if verbose:
  printMessage('Moving output file from temporary directory to user specified location')
shutil.move(os.path.join(temp_dir, result_path), sys.argv[4])

# Don't leave a trace
delTempDir(temp_dir, verbose)

