# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '3.0.5.dev628+g49e520c06.d20230822'
__version_tuple__ = version_tuple = (3, 0, 5, 'dev628', 'g49e520c06.d20230822')
