#!/bin/bash
# Verify successful execution of "dwi2response dhollander"
#   when the gradient table is provided via the -grad option
# Ensure that outputs match those generated
#   using a prior version of the software

mrinfo BIDS/sub-01/dwi/sub-01_dwi.nii.gz \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval \
-export_grad_mrtrix tmp_grad.b

dwi2response dhollander BIDS/sub-01/dwi/sub-01_dwi.nii.gz \
-grad tmp_grad.b \
tmp_wm.txt tmp_gm.txt tmp_csf.txt \
-voxels tmp_voxels.mif

testing_diff_matrix tmp_wm.txt dwi2response/dhollander/default_wm.txt -abs 1e-2
testing_diff_matrix tmp_gm.txt dwi2response/dhollander/default_gm.txt -abs 1e-2
testing_diff_matrix tmp_csf.txt dwi2response/dhollander/default_csf.txt -abs 1e-2
testing_diff_image tmp_voxels.mif dwi2response/dhollander/default.mif.gz

