#!/bin/bash
# Verify successful execution of "dwi2response dhollander"
#   under default operation;
#   here the gradient table is included in the input image header
# Ensure that outputs match those generated
#   using a prior version of the software

mrconvert BIDS/sub-01/dwi/sub-01_dwi.nii.gz tmp_in.mif -strides 0,0,0,1 \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval

dwi2response dhollander tmp_in.mif tmp_wm.txt tmp_gm.txt tmp_csf.txt -voxels tmp_voxels.mif

testing_diff_matrix tmp_wm.txt dwi2response/dhollander/default_wm.txt -abs 1e-2
testing_diff_matrix tmp_gm.txt dwi2response/dhollander/default_gm.txt -abs 1e-2
testing_diff_matrix tmp_csf.txt dwi2response/dhollander/default_csf.txt -abs 1e-2
testing_diff_image tmp_voxels.mif dwi2response/dhollander/default.mif.gz

