#!/bin/bash
# Verify successful execution of "dwi2response fa"
#   where gradient table information is imported using the -grad option
# Ensure that outputs match those generated
#   using a prior version of the software

mrinfo BIDS/sub-01/dwi/sub-01_dwi.nii.gz \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval \
-export_grad_mrtrix tmp_grad.b

dwi2response fa BIDS/sub-01/dwi/sub-01_dwi.nii.gz \
-grad tmp_grad.b \
 tmp_out.txt -voxels tmp_voxels.mif -number 20

testing_diff_matrix tmp_out.txt dwi2response/fa/default.txt -abs 1e-2
testing_diff_image tmp_voxels.mif dwi2response/fa/default.mif.gz

