#!/bin/bash
# Verify successful execution of "dwi2response fa"
#   where the maximal spherical harmonic degree of the response function
#   is explicitly modified using the -lmax option
# Ensure that outputs match those generated
#   using a prior version of the software

dwi2response fa BIDS/sub-01/dwi/sub-01_dwi.nii.gz \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval \
-mask BIDS/sub-01/dwi/sub-01_brainmask.nii.gz \
tmp_out.txt -voxels tmp_voxels.mif -number 20 \
-lmax 6

testing_diff_matrix tmp_out.txt dwi2response/fa/lmax.txt -abs 1e-2
testing_diff_image tmp_voxels.mif dwi2response/fa/lmax.mif.gz

