#!/bin/bash
# Verify successful execution of "dwi2response fa"
#   where a manual FA threshold is specified
# Ensure that outputs match those generated
#   using a prior version of the software

dwi2response fa BIDS/sub-01/dwi/sub-01_dwi.nii.gz tmp_out.txt \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval \
-mask BIDS/sub-01/dwi/sub-01_brainmask.nii.gz \
voxels tmp_voxels.mif \
-number 20 \
-threshold 0.7 \
-force

testing_diff_matrix tmp_out.txt dwi2response/fa/threshold.txt -abs 1e-2
testing_diff_image tmp_voxels.mif dwi2response/fa/threshold.mif.gz

