#!/bin/bash
# Verify successful execution of "dwi2response manual"
#   under default operation,
#   where the diffusion gradient table is available within the image header
# Ensure that outputs match those generated
#   using a prior version of the software

mrconvert BIDS/sub-01/dwi/sub-01_dwi.nii.gz tmp_in.mif -strides 0,0,0,1 \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval \
-force

dwi2response manual tmp_in.mif dwi2response/fa/default.mif.gz tmp_out.txt -force

testing_diff_matrix tmp_out.txt dwi2response/manual/default.txt -abs 1e-2

