#!/bin/bash
# Verify successful execution of "dwi2response manual"
#   where the maximal spherical harmonic degree per b-value
#   is explicitly set using the -lmax option
# Ensure that outputs match those generated
#   using a prior version of the software

dwi2response manual BIDS/sub-01/dwi/sub-01_dwi.nii.gz dwi2response/fa/default.mif.gz tmp_out.txt \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval \
-lmax 0,2,4,6

testing_diff_matrix tmp_out.txt dwi2response/manual/lmax.txt -abs 1e-2

