#!/bin/bash
# Verify successful execution of "dwi2response manual"
#   where the set of unique b-values to be considered
#   is explicitly specified using the -shells option
# Ensure that outputs match those generated
#   using a prior version of the software

dwi2response manual BIDS/sub-01/dwi/sub-01_dwi.nii.gz dwi2response/fa/default.mif.gz tmp_out.txt \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval \
-shells 0,3000 \
-force

testing_diff_matrix tmp_out.txt dwi2response/manual/shells.txt -abs 1e-2

