#!/bin/bash
# Verify successful execution of "dwi2response msmt_5tt"
#   where image piping is used

# Input DWI and output voxel selection image are piped
mrconvert BIDS/sub-01/dwi/sub-01_dwi.nii.gz - \
-strides 0,0,0,1 \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval |

dwi2response msmt_5tt - BIDS/sub-01/anat/sub-01_5TT.nii.gz \
tmp_wm.txt tmp_gm.txt tmp_csf.txt -force \
-voxels - \
-pvf 0.9 | \
testing_diff_image - dwi2response/msmt_5tt/default.mif.gz

# Input 5TT image is piped
mrconvert BIDS/sub-01/anat/sub-01_5TT.nii.gz - | \
dwi2response msmt_5tt BIDS/sub-01/dwi/sub-01_dwi.nii.gz - \
tmp_wm.txt tmp_gm.txt tmp_csf.txt -force \
-voxels tmp.mif \
-pvf 0.9

testing_diff_image tmp.mif dwi2response/msmt_5tt/default.mif.gz

# Input directions image is piped
dwi2tensor BIDS/sub-01/dwi/sub-01_dwi.nii.gz - \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval \
-mask BIDS/sub-01/dwi/sub-01_brainmask.nii.gz | \
tensor2metric - -vector - | \
dwi2response msmt_5tt BIDS/sub-01/dwi/sub-01_dwi.nii.gz BIDS/sub-01/anat/sub-01_5TT.nii.gz \
tmp_wm.txt tmp_gm.txt tmp_csf.txt -force \
-voxels tmp.mif \
-dirs - \
-pvf 0.9

testing_diff_image tmp.mif dwi2response/msmt_5tt/default.mif.gz
