#!/bin/bash
# Verify successful execution of "dwi2response msmt_5tt"
#   where the maximal spherical harmonic degree per b-value shell
#   is set explicitly using the -lmax option
# Ensure that outputs match those generated
#   using a prior version of the software

dwi2response msmt_5tt BIDS/sub-01/dwi/sub-01_dwi.nii.gz BIDS/sub-01/anat/sub-01_5TT.nii.gz \
tmp_wm.txt tmp_gm.txt tmp_csf.txt \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval \
-lmax 0,2,4,6 \
-voxels tmp_voxels.mif \
-pvf 0.9 \
-force

testing_diff_matrix tmp_wm.txt dwi2response/msmt_5tt/lmax_wm.txt -abs 1e-2
testing_diff_matrix tmp_gm.txt dwi2response/msmt_5tt/lmax_gm.txt -abs 1e-2
testing_diff_matrix tmp_csf.txt dwi2response/msmt_5tt/lmax_csf.txt -abs 1e-2
testing_diff_image tmp_voxels.mif dwi2response/msmt_5tt/lmax.mif.gz

