#!/bin/bash
# Verify successful execution of "dwi2response msmt_5tt"
#   under default operation,
#   where the diffusion gradient table is available in the image header
# Ensure that outputs match those generated
#   using a prior version of the software

mrconvert BIDS/sub-01/dwi/sub-01_dwi.nii.gz tmp_in.mif -strides 0,0,0,1 \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval

dwi2response msmt_5tt tmp_in.mif BIDS/sub-01/anat/sub-01_5TT.nii.gz \
tmp_wm.txt tmp_gm.txt tmp_csf.txt \
-voxels tmp_voxels.mif \
-pvf 0.9

testing_diff_matrix tmp_wm.txt dwi2response/msmt_5tt/default_wm.txt -abs 1e-2
testing_diff_matrix tmp_gm.txt dwi2response/msmt_5tt/default_gm.txt -abs 1e-2
testing_diff_matrix tmp_csf.txt dwi2response/msmt_5tt/default_csf.txt -abs 1e-2
testing_diff_image tmp_voxels.mif dwi2response/msmt_5tt/default.mif.gz

