#!/bin/bash
# Verify successful execution of "dwi2response msmt_5tt"
#   when filesystem paths include whitespace characters
rm -rf "tmp scratch"

dwi2tensor BIDS/sub-01/dwi/sub-01_dwi.nii.gz - \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval \
-mask BIDS/sub-01/dwi/sub-01_brainmask.nii.gz | \
tensor2metric - -vector "tmp dirs.mif" -force

ln -s BIDS/sub-01/dwi/sub-01_dwi.nii.gz "tmp in.nii.gz"
ln -s BIDS/sub-01/dwi/sub-01_dwi.bvec "tmp in.bvec"
ln -s BIDS/sub-01/dwi/sub-01_dwi.bval "tmp in.bval"
ln -s BIDS/sub-01/anat/sub-01_5TT.nii.gz "tmp 5TT.nii.gz"

mkdir "tmp scratch"

dwi2response msmt_5tt "tmp in.nii.gz" "tmp 5TT.nii.gz" \
"tmp wm.txt" "tmp gm.txt" "tmp csf.txt" -force \
-fslgrad "tmp in.bvec" "tmp in.bval" \
-dirs "tmp dirs.mif" \
-voxels "tmp voxels.mif" \
-pvf 0.9 \
-scratch "tmp scratch"

testing_diff_matrix "tmp wm.txt" dwi2response/msmt_5tt/default_wm.txt -abs 1e-2
testing_diff_matrix "tmp gm.txt" dwi2response/msmt_5tt/default_gm.txt -abs 1e-2
testing_diff_matrix "tmp csf.txt" dwi2response/msmt_5tt/default_csf.txt -abs 1e-2
testing_diff_image "tmp voxels.mif" dwi2response/msmt_5tt/default.mif.gz

