#!/bin/bash
# Verify successful execution of "dwi2response msmt_5tt"
#   where a brain mask is explicitly provided
# Ensure that outputs match those generated
#   using a prior version of the software

dwi2response msmt_5tt BIDS/sub-01/dwi/sub-01_dwi.nii.gz BIDS/sub-01/anat/sub-01_5TT.nii.gz \
tmp_wm.txt tmp_gm.txt tmp_csf.txt \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval \
-mask BIDS/sub-01/dwi/sub-01_brainmask.nii.gz \
-voxels tmp_voxels.mif \
-pvf 0.9 \
-force

testing_diff_matrix tmp_wm.txt dwi2response/msmt_5tt/masked_wm.txt -abs 1e-2
testing_diff_matrix tmp_gm.txt dwi2response/msmt_5tt/masked_gm.txt -abs 1e-2
testing_diff_matrix tmp_csf.txt dwi2response/msmt_5tt/masked_csf.txt -abs 1e-2
testing_diff_image tmp_voxels.mif dwi2response/msmt_5tt/masked.mif.gz

