#!/bin/bash
# Verify successful execution of "dwi2response tax"
#   under default operation,
#   where the diffuson gradient table is provided via the -fslgrad option
# Ensure that outputs match those generated
#   using a prior version of the software

dwi2response tax tmp_in.mif tmp_out.txt -voxels tmp_voxels.mif \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval \
-force

testing_diff_matrix tmp_out.txt dwi2response/tax/default.txt -abs 1e-2
testing_diff_image tmp_voxels.mif dwi2response/tax/default.mif.gz

