#!/bin/bash
# Verify successful execution of "dwi2response tax"
#   where a brain mask is provided via the -mask option
# Ensure that outputs match those generated
#   using a prior version of the software

dwi2response tax BIDS/sub-01/dwi/sub-01_dwi.nii.gz tmp_out.txt -force \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval \
-mask BIDS/sub-01/dwi/sub-01_brainmask.nii.gz \
-voxels tmp_voxels.mif

testing_diff_matrix tmp_out.txt dwi2response/tax/masked.txt -abs 1e-2
testing_diff_image tmp_voxels.mif dwi2response/tax/masked.mif.gz

