#!/bin/bash
# Verify successful execution of "dwi2response tournier"
#   under default operation,
#   where the diffuson gradient table is provided in the image header
# Ensure that outputs match those generated
#   using a prior version of the software

mrconvert BIDS/sub-01/dwi/sub-01_dwi.nii.gz tmp_in.mif -strides 0,0,0,1 \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval

dwi2response tournier tmp_in.mif tmp_out.txt -voxels tmp_voxels.mif \
-number 20 \
-iter_voxels 200

testing_diff_matrix tmp_out.txt dwi2response/tournier/default.txt -abs 1e-2
testing_diff_image tmp_voxels.mif dwi2response/tournier/default.mif.gz

