#!/bin/bash
# Verify successful execution of "dwi2response tournier"
#   where the maximal spherical harmonic degree of the response function
#   is controlled via the -lmax option
# Ensure that outputs match those generated
#   using a prior version of the software

dwi2response tournier tmp_in.mif tmp_out.txt -voxels tmp_voxels.mif \
-number 20 \
-iter_voxels 200 \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval \
-lmax 6 \
-force

testing_diff_matrix tmp_out.txt dwi2response/tournier/lmax.txt -abs 1e-2
testing_diff_image tmp_voxels.mif dwi2response/tournier/lmax.mif.gz

