#!/bin/bash
# Verify successful execution of "dwi2response tournier"
#   under default operation,
#   where the diffuson gradient table is provided via the -fslgrad option
# Ensure that outputs match those generated
#   using a prior version of the software

dwi2response tournier BIDS/sub-01/dwi/sub-01_dwi.nii.gz tmp_out.txt -force \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval \
-voxels tmp_voxels.mif \
-number 20 \
-iter_voxels 200

testing_diff_matrix tmp_out.txt dwi2response/tournier/default.txt -abs 1e-2
testing_diff_image tmp_voxels.mif dwi2response/tournier/default.mif.gz

