#!/bin/bash
# Verify successful execution of "dwi2response tournier"
#   where image paths include whitespace characters

ln -s BIDS/sub-01/dwi/sub-01_dwi.nii.gz "tmp in.nii.gz"
ln -s BIDS/sub-01/dwi/sub-01_dwi.bvec "tmp in.bvec"
ln -s BIDS/sub-01/dwi/sub-01_dwi.bval "tmp in.bval"

dwi2response tournier "tmp in.mif" "tmp out.txt" -force \
-fslgrad "tmp in.bvec" "tmp in.bval" \
-voxels "tmp voxels.mif" \
-number 20 \
-iter_voxels 200

testing_diff_matrix "tmp out.txt" dwi2response/tournier/default.txt -abs 1e-2
testing_diff_image "tmp voxels.mif" dwi2response/tournier/default.mif.gz

