#!/bin/bash
# Ensure that the command executes successfully
#   when the -nointensity flag is specified,
#   such that the command only checks and corrects for
#   differences in header transforms
mrconvert BIDS/sub-01/dwi/sub-01_dwi.nii.gz tmp_in.mif -force \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval

dwicat tmp_in.mif tmp_in.mif tmp_out.mif -nointensity -force

testing_diff_image tmp_out.mif $(mrcat tmp_in.mif tmp_in.mif -axis 3 -)
