#!/bin/bash
# Verify fixel2fixel command under usage:
# - Legacy fixel-fixel correspondence algorithm
# - Counting the number of subject fixels contributing to each template fixel
#   (note that this will never exceed one given use of the legacy mapping algorithm)
# Ensure that output matches that produced by the 3.0.x version of the fixelcorrespondence command:
#   the output FD fixel data file was thresholded in order to store 0 for template fixels where no subject fixel was selected,
#   and 1 for template fixels where a subject fixel was selected.

rm -rf tmp/
mkdir tmp/
cp fixel2fixel/directions.mif tmp/
cp fixel2fixel/index.mif tmp/

fixel2fixel fixelcorrespondence/session1/fd.mif fixelcorrespondence/mapping_legacy_s1.npz count tmp/ count_s1.mif
fixel2fixel fixelcorrespondence/session3/fd.mif fixelcorrespondence/mapping_legacy_s3.npz count tmp/ count_s3.mif

testing_diff_image tmp/count_s1.mif fixel2fixel/count_legacy_s1.mif -abs 0
testing_diff_image tmp/count_s3.mif fixel2fixel/count_legacy_s3.mif -abs 0
