#!/bin/bash
# Verify the -tiles option of "mrcheckerboardmask",
#   which controls the number of tiles in each dimension.
# Output is compared against reference data generated using a prior software version.
# NOTE: Reference data must be generated using a stable version of the software:
#   mrcheckerboardmask mask.mif -tiles 10 mrcheckerboardmask/tiles10.mif

mrcheckerboardmask mask.mif -tiles 2 - | \
testing_diff_image - mrcheckerboardmask/tiles2.mif
