#!/bin/bash
# Test the "dwinormalise group" algorithm
rm -rf tmp-dwi tmp-mask
mkdir tmp-dwi
mkdir tmp-mask

mrconvert BIDS/sub-02/dwi/sub-02_dwi.nii.gz tmp-dwi/sub-02.mif \
-fslgrad BIDS/sub-02/dwi/sub-02_dwi.bvec BIDS/sub-02/dwi/sub-02_dwi.bval
mrconvert BIDS/sub-02/dwi/sub-02_brainmask.nii.gz tmp-mask/sub-02.mif

mrconvert BIDS/sub-03/dwi/sub-03_dwi.nii.gz tmp-dwi/sub-03.mif \
-fslgrad BIDS/sub-03/dwi/sub-03_dwi.bvec BIDS/sub-03/dwi/sub-03_dwi.bval
mrconvert BIDS/sub-03/dwi/sub-03_brainmask.nii.gz tmp-mask/sub-03.mif 

dwinormalise group tmp-dwi/ tmp-mask/ tmp-group/ tmp-fa.mif tmp-mask.mif -force

testing_diff_image tmp-group/sub-02.mif dwinormalise/group/sub-02.mif.gz -frac 1e-2
testing_diff_image tmp-group/sub-03.mif dwinormalise/group/sub-03.mif.gz -frac 1e-2
testing_diff_image tmp-fa.mif dwinormalise/group/fa.mif.gz -abs 1e-3

# Include some tolerance for spatial differences in exemplar voxel selection
mrfilter tmp-mask.mif smooth tmp-masksource-smooth.mif -force
mrfilter dwinormalise/group/mask.mif.gz smooth tmp-masktarget-smooth.mif -force
testing_diff_image tmp-masksource-smooth.mif tmp-masktarget-smooth.mif -abs 0.3
