#!/bin/bash
# Test the "dwinormalise group" algorithm
#   when used in conjunction with image piping
rm -rf tmp-dwi tmp-mask
mkdir tmp-dwi
mkdir tmp-mask

mrconvert BIDS/sub-02/dwi/sub-02_dwi.nii.gz tmp-dwi/sub-02.mif \
-fslgrad BIDS/sub-02/dwi/sub-02_dwi.bvec BIDS/sub-02/dwi/sub-02_dwi.bval
mrconvert BIDS/sub-02/dwi/sub-02_brainmask.nii.gz tmp-mask/sub-02.mif

mrconvert BIDS/sub-03/dwi/sub-03_dwi.nii.gz tmp-dwi/sub-03.mif \
-fslgrad BIDS/sub-03/dwi/sub-03_dwi.bvec BIDS/sub-03/dwi/sub-03_dwi.bval
mrconvert BIDS/sub-03/dwi/sub-03_brainmask.nii.gz tmp-mask/sub-03.mif

# Output FA image is piped
dwinormalise group tmp-dwi/ tmp-mask/ tmp-group - tmp-mask.mif -force | \
testing_diff_image - dwinormalise/group/fa.mif.gz -abs 1e-3

# Output mask image is piped
dwinormalise group tmp-dwi/ tmp-mask/ tmp-group tmp-fa.mif - -force | \
mrfilter - smooth - |
testing_diff_image - $(mrfilter dwinormalise/group/mask.mif.gz smooth -) -abs 0.3
