#!/bin/bash
# Verify default operation of the "dwinormalise manual" algorithm
#   where image paths include whitespace characters

# Input and output DWI series are both piped
ln -s BIDS/sub-01/dwi/sub-01_dwi.nii.gz "tmp in.mif"
ln -s BIDS/sub-01/dwi/sub-01_dwi.bvec "tmp in.bvec"
ln -s BIDS/sub-01/dwi/sub-01_dwi.bval "tmp in.bval"
ln -s BIDS/sub-01/dwi/sub-01_brainmask.nii.gz "tmp mask.nii.gz"

dwinormalise manual "tmp in.mif" "tmp mask.nii.gz" "tmp out.mif" -force \
-fslgrad "tmp in.bvec" "tmp in.bval"

testing_diff_image "tmp out.mif" dwinormalise/manual/out.mif.gz -frac 1e-5
