#!/bin/bash
# Verify default operation of the "dwinormalise mtnorm" command
dwinormalise mtnorm BIDS/sub-01/dwi/sub-01_dwi.nii.gz tmpout.mif -force \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval \
-scale tmpscale.txt

testing_diff_image tmpout.mif dwinormalise/mtnorm/default_out.mif.gz -frac 1e-5
testing_diff_matrix tmpscale.txt dwinormalise/mtnorm/default_scale.txt -abs 1e-5
