#!/bin/bash
# Evaluate population template construction for:
# - 3D input images (Fractional Anisotropy (FA) maps)
# - Include mask image per input
# - Engage exclusively rigid-body registration
rm -rf tmp-fa tmp-mask
mkdir tmp-fa
mkdir tmp-mask

mrconvert BIDS/sub-02/dwi/sub-02_brainmask.nii.gz tmp-mask/sub-02.mif
mrconvert BIDS/sub-03/dwi/sub-03_brainmask.nii.gz tmp-mask/sub-03.mif
dwi2tensor BIDS/sub-02/dwi/sub-02_dwi.nii.gz - \
-fslgrad BIDS/sub-02/dwi/sub-02_dwi.bvec BIDS/sub-02/dwi/sub-02_dwi.bval \
-mask BIDS/sub-02/dwi/sub-02_brainmask.nii.gz | \
tensor2metric - -fa tmp-fa/sub-02.mif
dwi2tensor BIDS/sub-03/dwi/sub-03_dwi.nii.gz - \
-fslgrad BIDS/sub-03/dwi/sub-03_dwi.bvec BIDS/sub-03/dwi/sub-03_dwi.bval \
-mask BIDS/sub-03/dwi/sub-03_brainmask.nii.gz | \
tensor2metric - -fa tmp-fa/sub-03.mif

population_template tmp-fa/ tmp-template.mif -type rigid -mask_dir tmp-mask/ -template_mask tmp-mask.mif -force

testing_diff_image tmp-template.mif population_template/fa_rigid_template.mif.gz -abs 0.01

testing_diff_image -abs 0.3 \
$(mrfilter tmp-mask.mif smooth -)
$(mrfilter population_template/fa_rigid_mask.mif.gz smooth -)
