#!/bin/bash
# Evaluate population template construction when manually specifying
#   the desired template image voxel size
# - 3D input images (Fractional Anisotropy (FA) maps)
# - Include mask image per input for speed
# - Default registration type (rigid-body, then affine, then non-linear)
rm -rf tmp-fa tmp-mask
mkdir tmp-fa
mkdir tmp-mask

mrconvert BIDS/sub-02/dwi/sub-02_brainmask.nii.gz tmp-mask/sub-02.mif
mrconvert BIDS/sub-03/dwi/sub-03_brainmask.nii.gz tmp-mask/sub-03.mif
dwi2tensor BIDS/sub-02/dwi/sub-02_dwi.nii.gz - \
-fslgrad BIDS/sub-02/dwi/sub-02_dwi.bvec BIDS/sub-02/dwi/sub-02_dwi.bval \
-mask BIDS/sub-02/dwi/sub-02_brainmask.nii.gz | \
tensor2metric - -fa tmp-fa/sub-02.mif
dwi2tensor BIDS/sub-03/dwi/sub-03_dwi.nii.gz - \
-fslgrad BIDS/sub-03/dwi/sub-03_dwi.bvec BIDS/sub-03/dwi/sub-03_dwi.bval \
-mask BIDS/sub-03/dwi/sub-03_brainmask.nii.gz | \
tensor2metric - -fa tmp-fa/sub-03.mif

population_template tmp-fa/ tmp-template.mif -voxel_size 4.8 -mask_dir tmp-mask/ -template_mask tmp-mask.mif -force

testing_diff_image tmp-template.mif population_template/fa_voxelsize_template.mif.gz -abs 0.01

testing_diff_image -abs 0.3 \
$(mrfilter tmp-mask.mif smooth -) \
$(mrfilter population_template/fa_voxelsize_mask.mif.gz smooth -)
