#!/bin/bash
# Evaluate operation of population_template command
#   where image piping is utilised

rm -rf tmp-fa
mkdir tmp-fa

dwi2tensor BIDS/sub-02/dwi/sub-02_dwi.nii.gz - \
-fslgrad BIDS/sub-02/dwi/sub-02_dwi.bvec BIDS/sub-02/dwi/sub-02_dwi.bval \
-mask BIDS/sub-02/dwi/sub-02_brainmask.nii.gz | \
tensor2metric - -fa tmp-fa/sub-02.mif
dwi2tensor BIDS/sub-03/dwi/sub-03_dwi.nii.gz - \
-fslgrad BIDS/sub-03/dwi/sub-03_dwi.bvec BIDS/sub-03/dwi/sub-03_dwi.bval \
-mask BIDS/sub-03/dwi/sub-03_brainmask.nii.gz | \
tensor2metric - -fa tmp-fa/sub-03.mif

# Output template image is a pipe
population_template tmp-fa/ - | \
testing_diff_image - population_template/fa_default_template.mif.gz -abs 0.01

# Output template mask is a pipe
population_template tmp-fa/ tmp.mif -force \
-template_mask - | \
testing_diff_image $(mrfilter - smooth -) $(mrfilter population_template/fa_masked_mask.mif.gz smooth -) -abs 0.3
