#!/bin/bash
# Verify basic operation of command
# Outcome is compared to that calculated using a prior software version
tsfsmooth afd.tsf -stdev 2 tmp.tsf -force
testing_diff_tsf tmp.tsf tsfsmooth/out.tsf -frac 1e-5
