#!/bin/bash
# Verification of default operation of command,
#   run on a subset FoV of in vivo data
# Output is compared to that generated using a prior software version
rm -rf tmp/
tck2fixel tracks.tck fixel_image tmp/ tdi.mif
testing_diff_image tmp/tdi.mif tck2fixel/default.mif -abs 0.5
