#!/usr/bin/env python

import sys

varlist =  [ ]

for line in sys.stdin:
  if line.startswith ('name:'):
    varlist += [ [ line[6:].strip(), '', '' ] ]
  else:
    varlist[-1][1] += line

varlist.sort()

string = '.. _environment_variables:\n'
string += '\n'
string += '##########################################\n'
string += 'List of MRtrix3 environment variables\n'
string += '##########################################\n\n'

for entry in varlist:
  string += '*  **' + entry[0] + '**\n'
  for line in entry[2].splitlines():
    string += '     ' + line + '\n'
  string += '\n'

sys.stdout.write(string)
