#!/usr/bin/env python

import sys

varlist =  [ ]

for line in sys.stdin:
  line = line.split ('//ENVVAR')[1][1:]
  if line.startswith ('name:'):
    varlist += [ [ line[6:].strip(), '', '' ] ]
  else:
    varlist[-1][1] += line.rstrip() + '\n'

varlist.sort()

string = '.. _environment_variables:\n'
string += '\n'
string += '##########################################\n'
string += 'List of MRtrix3 environment variables\n'
string += '##########################################\n\n'

for entry in varlist:
  string += '.. envvar:: ' + entry[0] + '\n\n'
  for line in entry[1].splitlines():
    string += '     ' + line + '\n'
  string += '\n'

sys.stdout.write(string)
