#!/bin/bash
# Verify operation composing an affine and nonlinear transformation
# Outcome is compared to that generated using a prior software version
transformcompose rotatez.txt unit_warp.mif - | \
testing_diff_image - transformcompose/out2.mif -frac 0.001
