#!/bin/bash
# Verify successful execution of "dwi2mask 3dautomask"
#   where image paths include whitespace characters
# Make sure that the output image appears at the expected location
rm -f "tmp in.mif"
rm -rf "tmp scratch"

ln -s BIDS/sub-01/dwi/sub-01_dwi.nii.gz "tmp in.nii.gz"
ln -s BIDS/sub-01/dwi/sub-01_dwi.bvec "tmp in.bvec"
ln -s BIDS/sub-01/dwi/sub-01_dwi.bval "tmp in.bval"
mkdir "tmp scratch"

dwi2mask 3dautomask "tmp in.nii.gz" "tmp out.mif" -force \
-fslgrad "tmp in.bvec" "tmp in.bval" \
-scratch "tmp scratch"

ls | grep "^tmp out\.mif$"
