#!/bin/bash
# Verify that command "dwi2mask ants" executes to completion
#   when utilising image pipes

# Input and output images are pipes
mrconvert BIDS/sub-01/dwi/sub-01_dwi.nii.gz - \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval | \
dwi2mask ants - - \
-template dwi2mask/template_image.mif.gz dwi2mask/template_mask.mif.gz | \
mrconvert - tmp.mif -force

# Input template image is a pipe
mrconvert dwi2mask/template_image.mif.gz - | \
dwi2mask ants BIDS/sub-01/dwi/sub-01_dwi.nii.gz tmp.mif -force \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval \
-template - dwi2mask/template_mask.mif.gz

# Input template mask is a pipe
mrconvert dwi2mask/template_mask.mif.gz - | \
dwi2mask ants BIDS/sub-01/dwi/sub-01_dwi.nii.gz tmp.mif -force \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval \
-template dwi2mask/template_image.mif.gz -
