#!/bin/bash
# Verify operation of "dwi2mask b02template" command,
#   when the chosen underlying software is "fsl",
#   which utilises FSL commands flirt and fnirt.
# Apart from manually providing the template image and corresponding mask at the command-line,
#   all other script behaviour is left as default.
dwi2mask b02template BIDS/sub-01/dwi/sub-01_dwi.nii.gz tmp.mif -force \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval \
-software fsl \
-template dwi2mask/template_image.mif.gz dwi2mask/template_mask.mif.gz
