#!/bin/bash
# Ensure correct operation of the "dwi2mask legacy" command
#   when image paths that include whitespace characters are used
rm -rf "tmp scratch"

ln -s BIDS/sub-01/dwi/sub-01_dwi.nii.gz "tmp in.nii.gz"
ln -s BIDS/sub-01/dwi/sub-01_dwi.bvec "tmp in.bvec"
ln -s BIDS/sub-01/dwi/sub-01_dwi.bval "tmp in.bval"

mkdir "tmp scratch"

dwi2mask legacy "tmp in.nii.gz" "tmp out.mif" -force \
-fslgrad "tmp in.bvec" "tmp in.bval" \
-scratch "tmp scratch"

testing_diff_image "tmp out.mif" dwi2mask/legacy.mif.gz
