#!/bin/bash
# Verify successful execution of "dwi2mask synthstrip" algorithm,
#   when a range of different command-line options are included in the invocation
dwi2mask synthstrip BIDS/sub-01/dwi/sub-01_dwi.nii.gz tmpmask.mif -force \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval \
-stripped tmpstripped.mif \
-gpu -nocsf -border 0
