#!/bin/bash
# Ensure that if a vertex is not a member of any polygon,
#   the correct error message is produced.

# Data committed to test_data repo rather than generating on-the-fly
#   due to differences between BSD and Unix sed
#sed '5c\POINTS 643 float' meshconvert/in_ascii.vtk | \
#sed '648i\0.0 0.0 0.0' > meshvalidate/disconnected_vertex.vtk

rm -f tmp.txt
! ( meshvalidate meshvalidate/disconnected_vertex.vtk > tmp.txt 2>&1 )
cat tmp.txt
grep -E "Mesh \".+\": 1 vertex is not referenced by any polygon \\(disconnected vertex\\)" tmp.txt
