#!/bin/bash
# REFERENCE: generate with: mrtransform moving.mif.gz -flip 0 mrtransform/out_flip.mif.gz -force
# Verify the -flip option which flips the image along the specified axis
# Flipping along axis 0 (x-axis) modifies the header transform
# Outcome is compared against that generated using a prior software version
mrtransform moving.mif.gz -flip 0 - | \
testing_diff_image - mrtransform/out_flip.mif.gz -frac 1e-5
