#!/bin/bash
# Verify basic operation of the command
#   when cleanup is activated
rm -rf tmp/
mkdir tmp/

touch tmp/not_a_tempfile.txt
touch tmp/mrtrix-tmp-ABCDEF.mif
mkdir tmp/not_a_scratchdir/
mkdir tmp/command-tmp-ABCDEF/

mrtrix_cleanup tmp/
# The temporary file & scratch directory should have been erased,
#   and the two items that do not conform to those naming conventions preserved
[ "$(ls tmp/ | wc -l)" -eq 2 ]
ls tmp/ | grep -q "^not_a_tempfile\.txt$"
ls tmp/ | grep -q "^not_a_scratchdir$"
