#!/bin/bash
# Verify basic operation of the command
rm -rf tmp/
mkdir tmp/

touch tmp/not_a_tempfile.txt
touch tmp/mrtrix-tmp-ABCDEF.mif
mkdir tmp/not_a_scratchdir/
mkdir tmp/command-tmp-ABCDEF/

mrtrix_cleanup tmp/ -test
# In test mode nothing should be erased,
#   including those items that the command identifies as temporaries
[ "$(ls tmp/ | wc -l)" -eq 4 ]
ls tmp/ | grep -q "^mrtrix-tmp-ABCDEF\.mif$"
ls tmp/ | grep -q "^command-tmp-ABCDEF$"
