#!/bin/bash
# Verify operation of the command
#   when filesystem paths include whitespace characters
rm -rf "tmp in/"
mkdir "tmp in/"

touch "tmp in/not a tempfile.txt"
touch "tmp in/mrtrix-tmp-ABCDEF.mif"
mkdir "tmp in/not a scratchdir/"
mkdir "tmp in/command-tmp-ABCDEF/"

mrtrix_cleanup "tmp in/"
# The temporary file & scratch directory should have been erased,
#   and the two items that do not conform to those naming conventions preserved
[ "$(ls "tmp in/" | wc -l)" -eq 2 ]
ls "tmp in/" | grep -q "^not a tempfile\.txt$"
ls "tmp in/" | grep -q "^not a scratchdir$"
