#!/bin/bash
# Verify that tcksift correctly subsets a TRX tractogram,
# achieving the same density balance as when operating on TCK input.
# The SIFT phantom has two bundles of unequal length; after SIFT the
# density (TDI) of both bundles should be approximately equal.
rm -rf tmp_debug/
tcksift SIFT_phantom/tracks.trx SIFT_phantom/fods.mif tmp.trx -output_debug tmp_debug/ -csv tmp.csv -force
tckconvert tmp.trx tmp.tck -force
tckmap tmp.tck -template SIFT_phantom/mask.mif -precise tmp.mif -force
mrstats tmp.mif -mask SIFT_phantom/upper.mif -output mean > tmp1.txt
mrstats tmp.mif -mask SIFT_phantom/lower.mif -output mean > tmp2.txt
testing_diff_matrix tmp1.txt tmp2.txt -abs 10
