#!/bin/bash
# Verify "max" operator when applied along the axis of a single image
# Outcome is compared against that calculated using a prior software version
dwiextract dwi.mif - | \
mrmath - max -axis 3 - | \
testing_diff_image - mrmath/out_max.mif -frac 1e-5
