#!/bin/bash
# REFERENCE: generate with: mrmath dwi.mif min -axis 3 mrmath/out_min.mif -force
# Verify "min" operator when applied along the axis of a single image
# Outcome is compared against that calculated using a prior software version
mrmath dwi.mif min -axis 3 - | \
testing_diff_image - mrmath/out_min.mif -frac 1e-5
