#!/bin/bash
# Verify default operation of "tckstats",
#   reporting a table of streamline length statistics to stdout.
# Checks that the expected column headers are present.

rm -f tmp.txt
tckstats tracks.tck 2>&1 | tee tmp.txt
grep -E "mean" tmp.txt
grep -E "median" tmp.txt
grep -E "count" tmp.txt
