#!/bin/bash
# Verify default operation of "5ttgen deep_atropos"
#   where input image is the segmentation label image
#   and the brain stem is allocated to WM rather than 5th volume
# Outcome is compared to that generated using a prior software version
5ttgen deep_atropos 5ttgen/deep_atropos/segmentation_image.nii.gz - -white_stem | \
testing_diff_image - 5ttgen/deep_atropos/fromseg_whitestem.mif.gz
