#!/bin/bash
# Verify "5ttgen freesurfer" operation when the -nocrop option is specified
5ttgen freesurfer BIDS/sub-01/anat/aparc+aseg.mgz - -nocrop | \
testing_diff_image - 5ttgen/freesurfer/nocrop.mif.gz
