#!/bin/bash
# Verify default operation of "5ttgen freesurfer"
#   when the -first option is used;
#   and the FIRST output directory is provided as input,
#   such that the delineated surfaces are used to produce partial volume maps;
#   additionally FIRST was run on a NIfTI image
#   that was produced by taking the T1w image in the FreeSurfer LIA coordinate system,
#   and inverting the first axis in order to change coordinate system handedness
# Outcome is compared to that generated using a prior software version
5ttgen freesurfer freesurfer/sub-01/mri/aparc+aseg.mgz tmp.mif -force \
    -first freesurfer/sub-01/first/RIA
testing_diff_image tmp.mif 5ttgen/freesurfer/first_pvf.mif.gz
