#!/bin/bash
# Verify "5ttgen freesurfer" operation when the -sgm_amyg_hipp option is specified
5ttgen freesurfer BIDS/sub-01/anat/aparc+aseg.mgz - -sgm_amyg_hipp | \
testing_diff_image - 5ttgen/freesurfer/sgm_amyg_hipp.mif.gz
