#!/bin/bash
# Verify "5ttgen hsvs" operation when the segmentation of hippocampi and thalami
#   are explicitly requested to be performed using FSL FIRST
5ttgen hsvs freesurfer/sub-01 - -hippocampi first -thalami first | \
testing_diff_header - 5ttgen/hsvs/first.mif.gz
