#!/bin/bash
# Verify "5ttgen hsvs" operation when the 5TT image is generated on a user-specified template voxel grid
5ttgen hsvs freesurfer/sub-01 - -template BIDS/sub-01/anat/sub-01_T1w.nii.gz | \
testing_diff_header - 5ttgen/hsvs/template.mif.gz
