#!/bin/bash
# Verify "5ttgen msmt" default operation
# Output is compared to a prior output generateed by the command

# First we need to get some multi-tissue ODFs
dwi2response dhollander BIDS/sub-01/dwi/sub-01_dwi.nii.gz tmp_wm.txt tmp_gm.txt tmp_csf.txt \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval \
-mask BIDS/sub-01/dwi/sub-01_brainmask.nii.gz \
-force
dwi2fod msmt_csd BIDS/sub-01/dwi/sub-01_dwi.nii.gz \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval \
tmp_wm.txt tmp_wm.mif \
tmp_gm.txt tmp_gm.mif \
tmp_csf.txt tmp_csf.mif \
-force

5ttgen msmt tmp_wm.mif tmp_gm.mif tmp_csf.mif tmp.mif -force

testing_diff_image tmp.mif 5ttgen/msmt/default.mif.gz -abs 1e-5
