name: clang-tidy-enforce

on:
  pull_request:
    types: [opened, synchronize]
    branches: [master, dev]
  merge_group:
    types: [checks_requested]
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  clang-tidy-enforce:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install qt6-base-dev libqt6opengl6-dev libglvnd-dev libeigen3-dev zlib1g-dev libfftw3-dev ninja-build

    - name: Run CMake
      run: cmake . -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

    - uses: ZedThree/clang-tidy-review@v0.21.0
      with:
        apt_packages: g++,qt6-base-dev,libqt6opengl6-dev,libglvnd-dev,zlib1g-dev,libfftw3-dev,ninja-build
        config_file: .clang-tidy-enforce
        clang_tidy_version: 16
        fail_on_error: true
