#!/bin/bash
# Evaluate the operation of the "demodulate" filter when:
# - Input is a *4D* image series
# - Using *linear* phase map estimation
# - Phase maps are to be estimated based on *3D volumes*
#   (even though this is inappropriate for the input data)
mrfilter mrfilter/demodulate/in.mif.gz demodulate - -linear -axes 0,1,2 | \
    testing_diff_image - mrfilter/demodulate/linear_3Ddemod.mif.gz -frac 1e-6
