#!/bin/bash
# Verify the "normalise" filter using default settings
# The normalisation filter divides each voxel intensity by the local neighbourhood mean
# Outcome is compared against that generated using a prior software version
mrfilter b0.nii.gz normalise - | \
testing_diff_image - mrfilter/normalise.mif -frac 1e-5
