#!/bin/bash
# Test generating connection exemplar streamlines
#   for a pair of nodes, writing a single output track file.
# The assignments file is the reference output from the tck2connectome test.
# The parcellation image is used to constrain exemplar endpoints.
# The test verifies that the command runs successfully and produces a valid track file.
connectome2tck SIFT_phantom/tracks.tck tck2connectome/assignments.csv tmp.tck \
    -nodes 1,2 \
    -exclusive \
    -files single \
    -exemplars SIFT_phantom/parc.mif \
    -force

tckvalidate tmp.tck
