#!/bin/bash
# Verify operation of command when the -invert command-line flag is specified
# Outcome is compared to that calculated using a prior software version
tsfthreshold afd.tsf 0.2 -invert tmp.tsf -force
testing_diff_tsf tmp.tsf tsfthreshold/out2.tsf
