#!/bin/bash
# Verify successful execution of command under default configuration
dwibiasnormmask BIDS/sub-01/dwi/sub-01_dwi.nii.gz tmpout.mif tmpmask.mif -force \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval \
-output_bias tmpbias.mif \
-output_scale tmpscale.txt \
-output_tissuesum tmptissuesum.mif

testing_diff_image tmpout.mif dwibiasnormmask/default_out.mif.gz -frac 1e-5
testing_diff_image tmpmask.mif dwibiasnormmask/default_mask.mif.gz
testing_diff_image tmpbias.mif dwibiasnormmask/default_bias.mif.gz -frac 1e-5
testing_diff_matrix tmpscale.txt dwibiasnormmask/default_scale.txt -frac 1e-5
testing_diff_image tmptissuesum.mif dwibiasnormmask/default_tissuesum.mif.gz -abs 1e-5
