#!/bin/bash
# Verify successful execution of command
#   when used in conjunction with image pipes

# Input DWI series, and output DWI series, are pipes
mrconvert BIDS/sub-01/dwi/sub-01_dwi.nii.gz - \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval | \
dwibiasnormmask - - tmp_mask.mif -force | \
testing_diff_image - dwibiasnormmask/default_out.mif.gz -frac 1e-5

# Prepare some input data to be subsequently used in multiple tests
mrconvert BIDS/sub-01/dwi/sub-01_dwi.nii.gz tmp_in.mif -force \
-fslgrad BIDS/sub-01/dwi/sub-01_dwi.bvec BIDS/sub-01/dwi/sub-01_dwi.bval \
-strides 0,0,0,1

# Input initial mask is a pipe
# Both outputs are erased beforehand and their presence verified afterwards,
#   since no other aspect of this invocation's result is compared against reference data
rm -f tmp_out.mif tmp_mask.mif
mrconvert BIDS/sub-01/dwi/sub-01_brainmask.nii.gz - | \
dwibiasnormmask tmp_in.mif tmp_out.mif tmp_mask.mif -force \
-init_mask -

ls | grep "^tmp_out\.mif$"
ls | grep "^tmp_mask\.mif$"

# Output mask is a pipe
dwibiasnormmask tmp_in.mif tmp_out.mif - -force | \
testing_diff_image - dwibiasnormmask/default_mask.mif.gz

# Output bias field image is a pipe
dwibiasnormmask tmp_in.mif tmp_out.mif tmp_mask.mif -force \
-output_bias - | \
testing_diff_image - dwibiasnormmask/default_bias.mif.gz -frac 1e-5

# Output tissue sum image is a pipe
dwibiasnormmask tmp_in.mif tmp_out.mif tmp_mask.mif -force \
-output_tissuesum - | \
testing_diff_image - dwibiasnormmask/default_tissuesum.mif.gz -abs 1e-5
